import type { PageNode } from "./types";

/**
 * Content graph seed — every node must link out via `related`.
 * Heartbeat passes append more nodes and densify edges.
 */
export const catalog: PageNode[] = [
  {
    slug: "what-is-dogecoin",
    title: "What is Dogecoin?",
    pillar: "clarity",
    hub: true,
    summary: "A plain-English map of DOGE: coin, culture, and why it still matters.",
    hook: "You already know the meme. Here’s the machine underneath it.",
    tags: ["basics", "intro", "doge"],
    related: [
      "how-dogecoin-works",
      "dogecoin-vs-bitcoin",
      "doge-glossary",
      "why-uk-domain",
      "is-dogecoin-a-joke",
    
      "tipping-culture",
      "dogecoin-history",
      "forks-and-clones",
      "uk-search-intent",],
    body: [
      "Dogecoin is a cryptocurrency that started as a joke and became a living culture. The coin moves on a public network; the meme moves through people.",
      "You do not need a finance degree to hold a mental model. DOGE is digital cash with a community that prizes humour, tips, and approachability over gatekeeping.",
      "This site exists because UK searchers keep arriving with the same quiet question: what is this, really — and how do I engage without getting burned?",
      "Clarity first. Then safety. Then belonging. That order is intentional.",
    ],
  },
  {
    slug: "how-dogecoin-works",
    title: "How Dogecoin works",
    pillar: "clarity",
    summary: "Blocks, wallets, fees, and confirmations — without the textbook fog.",
    hook: "If you can follow a bank transfer, you can follow a DOGE send.",
    tags: ["basics", "network", "wallets"],
    related: [
      "what-is-dogecoin",
      "wallets-explained",
      "fees-and-speed",
      "mining-and-security",
      "seed-phrases",
    
      "confirmations-explained",
      "reading-block-explorers",
      "nodes-and-clients",
      "utxo-mental-model",],
    body: [
      "Dogecoin transactions are messages broadcast to a peer-to-peer network. Miners (and the wider network) race to order those messages into blocks.",
      "Your wallet does not ‘store coins like a purse.’ It stores keys that prove you can move balances recorded on the public ledger.",
      "A send is final after enough confirmations. Fees pay for inclusion priority. Speed is usually fine for everyday amounts; huge transfers deserve extra caution.",
      "When something feels magical, zoom out: it’s cryptography + incentives + open software — not vibes alone.",
    ],
  },
  {
    slug: "dogecoin-vs-bitcoin",
    title: "Dogecoin vs Bitcoin",
    pillar: "clarity",
    summary: "Same family tree, different temperament. Compare without tribal warfare.",
    hook: "Bitcoin is the cathedral. Dogecoin is the festival outside.",
    tags: ["compare", "bitcoin", "basics"],
    related: [
      "what-is-dogecoin",
      "inflation-and-supply",
      "is-dogecoin-a-joke",
      "why-people-buy-doge",
      "culture-and-memes",
    
      "forks-and-clones",],
    body: [
      "Both are proof-of-work cryptocurrencies. Bitcoin optimises for scarcity narrative and settlement gravity. Dogecoin optimises for approachability and cultural velocity.",
      "Supply design differs. That is not a moral verdict — it is a design choice with trade-offs for fees, miner incentives, and long-term story.",
      "If someone forces you to ‘pick a side,’ leave the thread. Useful comparison is about use-cases, not identity combat.",
      "For UK newcomers: learn Bitcoin’s security lessons, borrow Dogecoin’s human tone, and ignore the purity contests.",
    ],
  },
  {
    slug: "doge-glossary",
    title: "DOGE glossary",
    pillar: "clarity",
    summary: "The words people throw around — defined like a human wrote them.",
    hook: "Jargon is a velvet rope. Cut it.",
    tags: ["glossary", "basics"],
    related: [
      "what-is-dogecoin",
      "wallets-explained",
      "seed-phrases",
      "phishing-red-flags",
      "fees-and-speed",
    ],
    body: [
      "Wallet: software or hardware that manages keys. Exchange account: a company balance that is not the same as self-custody.",
      "Seed phrase: the master backup words. Anyone with them can empty the wallet. Never type them into a website.",
      "Gas/fees: payment to get your transaction included. DOGE fees are usually small, but ‘usually’ is not a promise.",
      "HODL, FOMO, rekt, rug: culture words. Learn them so scammers cannot hide behind slang.",
    ],
  },
  {
    slug: "wallets-explained",
    title: "Wallets explained (UK)",
    pillar: "clarity",
    summary: "Custodial vs self-custody, phone vs hardware, and what ‘not your keys’ means.",
    hook: "The wallet question is really a trust question.",
    tags: ["wallets", "custody", "uk"],
    related: [
      "seed-phrases",
      "self-custody-checklist",
      "exchange-vs-wallet",
      "how-dogecoin-works",
      "first-doge-checklist",
    
      "hardware-wallets",
      "mobile-wallet-hygiene",
      "open-source-trust",
      "hot-wallet-limits",
      "browser-extension-risk",],
    body: [
      "An exchange wallet is convenient and fragile: the company holds the keys. Fine for tiny experiments; poor as a life vault.",
      "A self-custody wallet puts responsibility on you. That is freedom and liability in the same box.",
      "Hardware wallets reduce malware risk for larger balances. Phone wallets are fine for learning amounts if you back up the seed offline.",
      "UK angle: keep records for your own sanity. This is not tax advice — it is future-you protection.",
    ],
  },
  {
    slug: "fees-and-speed",
    title: "Fees and speed",
    pillar: "clarity",
    summary: "What you pay, what you wait for, and when to slow down on purpose.",
    hook: "Cheap and fast is great — until you send to the wrong address.",
    tags: ["fees", "network"],
    related: [
      "how-dogecoin-works",
      "first-doge-checklist",
      "address-hygiene",
      "wallets-explained",
      "common-mistakes",
    
      "liquidity-basics",
      "test-transactions",
      "network-congestion",
      "utxo-mental-model",],
    body: [
      "Network fees buy priority. During quiet periods they are negligible. During chaos, patience beats panic.",
      "Confirmation time is not ‘instant like Apple Pay.’ Plan for minutes, not milliseconds, when it matters.",
      "Test with a tiny send before a large one. That single habit prevents more pain than any thread tip.",
      "If a stranger rushes you to skip the test send, that stranger is the risk.",
    ],
  },
  {
    slug: "mining-and-security",
    title: "Mining and network security",
    pillar: "clarity",
    summary: "Why miners exist, what they secure, and what they don’t promise.",
    hook: "Security is an incentive machine, not a vibe.",
    tags: ["mining", "security"],
    related: [
      "how-dogecoin-works",
      "inflation-and-supply",
      "dogecoin-vs-bitcoin",
      "what-is-dogecoin",
      "myths-to-ignore",
    
      "nodes-and-clients",],
    body: [
      "Miners expend energy to propose blocks. The network’s rules decide which history wins.",
      "Mining does not guarantee your personal OPSEC. It secures consensus, not your seed phrase hygiene.",
      "Hashrate stories are interesting. They are not investment theses by themselves.",
      "If you only remember one line: the chain can be robust while your habits are not.",
    ],
  },
  {
    slug: "inflation-and-supply",
    title: "Inflation and supply",
    pillar: "clarity",
    summary: "Dogecoin’s issuance model in calm language — trade-offs included.",
    hook: "‘Infinite’ is a meme. Issuance is a schedule.",
    tags: ["supply", "economics"],
    related: [
      "dogecoin-vs-bitcoin",
      "why-people-buy-doge",
      "myths-to-ignore",
      "what-is-dogecoin",
      "mining-and-security",
    ],
    body: [
      "Dogecoin continues to issue new coins over time. That design funds security and keeps the monetary story different from hard-cap maximalism.",
      "Whether that is ‘good’ depends on what you want money-like assets to do. There is no universal answer.",
      "Beware charts that treat issuance as destiny. Culture, liquidity, and attention also move price — and price is not this site’s product.",
      "Clarity means naming trade-offs out loud instead of selling certainty.",
    ],
  },
  {
    slug: "is-dogecoin-a-joke",
    title: "Is Dogecoin a joke?",
    pillar: "belonging",
    summary: "Yes — and also a serious network used by real humans. Both can be true.",
    hook: "The joke is the onboarding. The network is the machinery.",
    tags: ["culture", "myths"],
    related: [
      "culture-and-memes",
      "what-is-dogecoin",
      "why-people-buy-doge",
      "myths-to-ignore",
      "uk-community-pulse",
    
      "dogecoin-history",],
    body: [
      "Dogecoin began as satire. That origin is a feature: it lowers the intimidation tax that keeps people out of crypto.",
      "Treating it only as a joke can make you careless. Treating it only as sacred can make you cruel. Aim for warm precision.",
      "UK conversations often split between ‘it’s funny’ and ‘it’s dangerous.’ This site holds both truths without the shouting.",
      "Belonging here means you can laugh and still check the address twice.",
    ],
  },
  {
    slug: "culture-and-memes",
    title: "Culture and memes",
    pillar: "belonging",
    summary: "Shiba energy, tip culture, and why kindness became a brand asset.",
    hook: "Memes are the user interface for emotion.",
    tags: ["culture", "community"],
    related: [
      "is-dogecoin-a-joke",
      "uk-community-pulse",
      "much-wow-lexicon",
      "why-uk-domain",
      "what-is-dogecoin",
    
      "tipping-culture",
      "meme-literacy",],
    body: [
      "Dogecoin culture rewards tipping, charity bits, and not taking yourself too seriously — until money is on the line.",
      "Memes compress belonging. They also compress scams: fake giveaways wear the same costume.",
      "If a meme demands urgency, verify outside the meme. Fun is not a deadline.",
      "This pillar exists so newcomers feel welcomed without being softened up for fraud.",
    ],
  },
  {
    slug: "why-uk-domain",
    title: "Why dogecoin.co.uk exists",
    pillar: "belonging",
    hub: true,
    summary: "A UK front door: local signal, unofficial stance, calm tone.",
    hook: "People trust a postcode vibe before they trust a whitepaper.",
    tags: ["uk", "about", "trust"],
    related: [
      "unofficial-disclaimer",
      "uk-community-pulse",
      "what-is-dogecoin",
      "phishing-red-flags",
      "first-doge-checklist",
    
      "uk-search-intent",],
    body: [
      "dogecoin.co.uk is an unofficial community presence. It is not the Dogecoin Foundation and not a financial adviser.",
      "The `.co.uk` signal answers a psychological need: ‘is there a local, sane explanation?’ Yes — start here.",
      "We refuse price prophecy. We publish checklists, explainers, and culture notes you can actually use.",
      "If you only remember one sentence: warmth without hype is the brand.",
    ],
  },
  {
    slug: "unofficial-disclaimer",
    title: "Unofficial — on purpose",
    pillar: "belonging",
    summary: "Clear boundaries build trust faster than borrowed authority.",
    hook: "Saying what we are not is a feature.",
    tags: ["trust", "legal", "uk"],
    related: [
      "why-uk-domain",
      "not-financial-advice",
      "phishing-red-flags",
      "uk-community-pulse",
      "proof-matrix",
    ],
    body: [
      "This site is community-built and unofficial. That honesty is deliberate.",
      "Borrowed logos and fake ‘official support’ are classic scam costumes. We won’t wear them.",
      "When in doubt, verify claims through primary sources and slow down.",
      "Belonging includes protecting the pack from impostors — including us, if we ever sound off.",
    ],
  },
  {
    slug: "not-financial-advice",
    title: "Not financial advice",
    pillar: "safety",
    summary: "Education is not a recommendation to buy, sell, or hold.",
    hook: "If it sounds like a tip dressed as destiny, walk away.",
    tags: ["safety", "disclaimer"],
    related: [
      "unofficial-disclaimer",
      "why-people-buy-doge",
      "common-mistakes",
      "scam-patterns-uk",
      "first-doge-checklist",
    
      "uk-tax-mindset",
      "influencer-disclosures",],
    body: [
      "Nothing on dogecoin.co.uk is financial, tax, or legal advice. Crypto assets can go to zero.",
      "We explain mechanics and risks so you can think. We do not tell you what to do with money.",
      "If a page ever feels like pressure, treat that feeling as a warning light.",
      "Safety starts with refusing fake certainty.",
    ],
  },
  {
    slug: "phishing-red-flags",
    title: "Phishing red flags",
    pillar: "safety",
    hub: true,
    summary: "The patterns that empty wallets — spotted early.",
    hook: "Urgency is the scam’s favourite font.",
    tags: ["phishing", "scams", "safety"],
    related: [
      "scam-patterns-uk",
      "seed-phrases",
      "fake-giveaways",
      "support-impersonation",
      "address-hygiene",
    
      "onboarding-a-friend",
      "browser-extension-risk",],
    body: [
      "Nobody legitimate needs your seed phrase. Not support. Not a ‘sync’ page. Not a DM.",
      "Lookalike domains, fake wallet connect prompts, and ‘verification’ deadlines are industrial-scale traps.",
      "UK twist: SMS and email impersonating banks or exchanges spike during market chaos.",
      "When adrenaline rises, open a fresh bookmark to the real site — never the link in the message.",
    ],
  },
  {
    slug: "scam-patterns-uk",
    title: "Scam patterns in the UK",
    pillar: "safety",
    summary: "Local flavours of fraud: romance, investment, and ‘recovery’ cons.",
    hook: "The accent changes. The script doesn’t.",
    tags: ["scams", "uk", "safety"],
    related: [
      "phishing-red-flags",
      "fake-giveaways",
      "support-impersonation",
      "if-you-got-scammed",
      "self-custody-checklist",
    
      "social-engineering",],
    body: [
      "Investment scams promise guaranteed returns and a friendly mentor. Guaranteed returns in crypto are fiction.",
      "Recovery scams arrive after the first loss: ‘specialists’ who need fees to unlock funds. That is round two.",
      "Romance and social engineering use loneliness as an attack surface. Slow relationships beat fast wires.",
      "Report, document, and do not pay ‘unlock’ fees. Pride recovers slower than money — protect both.",
    ],
  },
  {
    slug: "seed-phrases",
    title: "Seed phrases",
    pillar: "safety",
    summary: "The master key: offline, boring, never photographed into the cloud.",
    hook: "If it’s typed into a website, it’s already compromised.",
    tags: ["seed", "custody", "safety"],
    related: [
      "self-custody-checklist",
      "wallets-explained",
      "phishing-red-flags",
      "common-mistakes",
      "first-doge-checklist",
    
      "paper-wallets",
      "mobile-wallet-hygiene",
      "family-and-inheritance",
      "backup-drill",],
    body: [
      "A seed phrase recreates your wallet. Treat it like the deed to a house written on paper.",
      "Write it offline. Store it where thieves and flatmates can’t casually find it. Consider metal backups for serious amounts.",
      "Never enter a seed to ‘fix,’ ‘claim,’ or ‘stop a penalty.’ Those words are theatre.",
      "If you already typed a seed into a site, move funds to a fresh wallet immediately — then retire the old one.",
    ],
  },
  {
    slug: "self-custody-checklist",
    title: "Self-custody checklist",
    pillar: "safety",
    summary: "A practical pre-flight before you hold your own keys.",
    hook: "Freedom without a checklist is cosplay.",
    tags: ["checklist", "custody"],
    related: [
      "seed-phrases",
      "wallets-explained",
      "exchange-vs-wallet",
      "address-hygiene",
      "first-doge-checklist",
    
      "paper-wallets",
      "multisig-basics",
      "family-and-inheritance",
      "backup-drill",],
    body: [
      "Download wallets from official sources you typed yourself. Verify you’re not in an app-store clone.",
      "Back up the seed before you fund the wallet. Test recovery on a spare device with dust amounts.",
      "Enable device passcodes and OS updates. Boring hygiene beats clever setups.",
      "Separate ‘learning money’ from ‘serious money.’ Different wallets, different emotional stakes.",
    ],
  },
  {
    slug: "exchange-vs-wallet",
    title: "Exchange vs wallet",
    pillar: "clarity",
    summary: "Convenience accounts versus keys you control — choose knowingly.",
    hook: "Both can be right. Confusion is what’s expensive.",
    tags: ["exchange", "wallets"],
    related: [
      "wallets-explained",
      "self-custody-checklist",
      "first-doge-checklist",
      "uk-buying-basics",
      "common-mistakes",
    
      "password-and-2fa",],
    body: [
      "Exchanges are on-ramps. They are also honeypots: large targets with human processes and outages.",
      "Self-custody removes company risk and adds personal responsibility risk. Pick consciously.",
      "A sane UK path for many beginners: buy small on a reputable venue, withdraw a learning amount to a wallet, practice sends.",
      "Leaving everything on an exchange ‘for now’ has a way of becoming forever. Set a date to decide.",
    ],
  },
  {
    slug: "first-doge-checklist",
    title: "First DOGE checklist",
    pillar: "safety",
    summary: "Your first week with Dogecoin — slow, reversible, ego-free.",
    hook: "Start tiny. Competence compounds faster than bravado.",
    tags: ["checklist", "beginner"],
    related: [
      "uk-buying-basics",
      "wallets-explained",
      "fees-and-speed",
      "phishing-red-flags",
      "what-is-dogecoin",
    
      "volatility-psychology",
      "onboarding-a-friend",
      "stable-habits",],
    body: [
      "Write your goal in one sentence: learn, tip, long curiosity, or something else. Goals prevent FOMO shopping.",
      "Fund only what you can emotionally delete. Then practice a receive, a send, and a backup restore.",
      "Turn off notification dopamine where you can. Price apps train panic.",
      "When you feel rushed, open the phishing page on this site before you click anything else.",
    ],
  },
  {
    slug: "uk-buying-basics",
    title: "Buying DOGE in the UK — basics",
    pillar: "clarity",
    summary: "High-level on-ramp ideas without platform cheerleading.",
    hook: "The buy button is easy. The aftermath is the curriculum.",
    tags: ["uk", "buy", "beginner"],
    related: [
      "first-doge-checklist",
      "exchange-vs-wallet",
      "not-financial-advice",
      "common-mistakes",
      "fees-and-speed",
    
      "liquidity-basics",
      "uk-tax-mindset",
      "market-orders-basics",],
    body: [
      "Use regulated, well-known venues you researched yourself. Avoid ‘too helpful’ strangers with referral urgency.",
      "Expect identity checks. That friction is often a safety feature, not a conspiracy.",
      "After purchase, decide custody deliberately. Default inertia favours the exchange.",
      "Again: not advice — a map of decisions you should make awake.",
    ],
  },
  {
    slug: "common-mistakes",
    title: "Common mistakes",
    pillar: "safety",
    summary: "The greatest hits of avoidable pain.",
    hook: "Most losses are procedural, not cosmic.",
    tags: ["mistakes", "safety"],
    related: [
      "address-hygiene",
      "seed-phrases",
      "fake-giveaways",
      "fees-and-speed",
      "first-doge-checklist",
    
      "volatility-psychology",],
    body: [
      "Sending to the wrong chain or address. Always verify the first and last characters slowly.",
      "Screenshotting seed phrases into camera rolls that sync to the cloud.",
      "Trusting ‘support’ that messages first.",
      "Sizing positions based on group chat courage instead of personal sleep quality.",
    ],
  },
  {
    slug: "address-hygiene",
    title: "Address hygiene",
    pillar: "safety",
    summary: "Copy, paste, verify — the ritual that saves fortunes.",
    hook: "Your clipboard is an attack surface.",
    tags: ["addresses", "opsec"],
    related: [
      "common-mistakes",
      "phishing-red-flags",
      "fees-and-speed",
      "wallets-explained",
      "self-custody-checklist",
    
      "test-transactions",
      "dust-and-spam",
      "qr-code-hygiene",],
    body: [
      "Malware can swap addresses on your clipboard. Verify on the device screen, not only in your head.",
      "Save known addresses with labels. Prefer QR for in-person where possible.",
      "For large moves: send dust, confirm receipt, then send the rest.",
      "If anything looks off by one character, abort. The network will not pity you.",
    ],
  },
  {
    slug: "fake-giveaways",
    title: "Fake giveaways",
    pillar: "safety",
    summary: "Double-your-DOGE theatres and reply-with-screenshot traps.",
    hook: "If you must send coins to receive coins, it’s not a gift.",
    tags: ["scams", "giveaways"],
    related: [
      "phishing-red-flags",
      "scam-patterns-uk",
      "support-impersonation",
      "culture-and-memes",
      "if-you-got-scammed",
    
      "charity-and-causes",
      "moderation-playbook",],
    body: [
      "Celebrity-face giveaways are industrial fraud. The real person is not in the replies.",
      "‘Send 10 get 20’ is not generosity — it’s a funnel.",
      "Meme culture makes these scams blend in. That is why belonging pages and safety pages must interlink.",
      "Mute, report, move on. Engagement is oxygen.",
    ],
  },
  {
    slug: "support-impersonation",
    title: "Support impersonation",
    pillar: "safety",
    summary: "Fake agents, ticket theatre, and screen-share disasters.",
    hook: "Real support rarely DMs first. Fake support always does.",
    tags: ["scams", "support"],
    related: [
      "phishing-red-flags",
      "scam-patterns-uk",
      "seed-phrases",
      "fake-giveaways",
      "if-you-got-scammed",
    ],
    body: [
      "Impersonators create urgency: locked account, suspicious login, refund window closing.",
      "They want remote access or seeds. Deny both. Hang up. Use official channels you typed.",
      "UK call spoofing exists. Caller ID is costume jewellery.",
      "Write down what happened. Patterns help others even when funds don’t return.",
    ],
  },
  {
    slug: "if-you-got-scammed",
    title: "If you got scammed",
    pillar: "safety",
    summary: "Damage control without shame spirals.",
    hook: "Shame is the scammer’s second product. Don’t buy it.",
    tags: ["recovery", "safety", "uk"],
    related: [
      "scam-patterns-uk",
      "phishing-red-flags",
      "seed-phrases",
      "self-custody-checklist",
      "uk-community-pulse",
    ],
    body: [
      "Move remaining funds to a new wallet if keys may be exposed. Rotate passwords and enable 2FA elsewhere.",
      "Contact your bank/exchange fraud teams quickly for fiat on-ramps. Document txids and screenshots.",
      "Ignore recovery DMs. They are predators hunting the injured.",
      "Tell one trusted human. Isolation makes the next scam easier.",
    ],
  },
  {
    slug: "why-people-buy-doge",
    title: "Why people buy DOGE",
    pillar: "belonging",
    summary: "Culture, humour, payments experiments, and yes — speculation. Named plainly.",
    hook: "Motives are mixed. Honesty beats branding.",
    tags: ["culture", "motives"],
    related: [
      "is-dogecoin-a-joke",
      "not-financial-advice",
      "culture-and-memes",
      "inflation-and-supply",
      "what-is-dogecoin",
    
      "influencer-disclosures",],
    body: [
      "Some buy for the joke. Some for the community. Some for speculation. Some for tipping experiments.",
      "None of those motives require you to pretend it’s risk-free.",
      "This site won’t moralise your motive. It will insist on safety literacy either way.",
      "Belonging means you can say ‘I don’t know yet’ without getting ejected from the pack.",
    ],
  },
  {
    slug: "uk-community-pulse",
    title: "UK community pulse",
    pillar: "belonging",
    hub: true,
    summary: "A living stub for meetups, tone, and local signal — without pretending we’re a foundation.",
    hook: "Local beats loud.",
    tags: ["uk", "community"],
    related: [
      "why-uk-domain",
      "culture-and-memes",
      "much-wow-lexicon",
      "unofficial-disclaimer",
      "join-the-list",
    
      "meetups-and-irl",
      "creators-and-builders",
      "community-moderation",],
    body: [
      "UK Dogecoin energy tends to be dryer humour, sharper scam awareness, and less carnival barking.",
      "We’ll grow this page with community notes, reading lists, and event pointers as they earn trust.",
      "If you run a meetup, lead with safety and clarity — belonging follows.",
      "Want updates? The join funnel on the home page is the quiet doorbell.",
    ],
  },
  {
    slug: "much-wow-lexicon",
    title: "Much wow lexicon",
    pillar: "belonging",
    summary: "Community phrases decoded so you can participate without cringe panic.",
    hook: "Speaking the dialect is optional. Understanding it is power.",
    tags: ["culture", "glossary"],
    related: [
      "culture-and-memes",
      "doge-glossary",
      "is-dogecoin-a-joke",
      "uk-community-pulse",
      "fake-giveaways",
    
      "meme-literacy",],
    body: [
      "Much wow / such scarce / very currency: playful broken English from early meme format. Affectionate, not illiteracy.",
      "To the moon: aspiration slang. Not a schedule.",
      "Tips and ‘do only good everyday’ point at the kinder strain of the culture — still verify before you click.",
      "When slang is used to rush a transaction, the dialect became a weapon. Switch to safety mode.",
    ],
  },
  {
    slug: "myths-to-ignore",
    title: "Myths to ignore",
    pillar: "clarity",
    summary: "Certainty cosplay, guaranteed returns, and other bedtime stories.",
    hook: "If it removes all doubt, it’s probably marketing.",
    tags: ["myths", "clarity"],
    related: [
      "inflation-and-supply",
      "is-dogecoin-a-joke",
      "not-financial-advice",
      "dogecoin-vs-bitcoin",
      "why-people-buy-doge",
    ],
    body: [
      "‘It’s too late’ and ‘it’s guaranteed’ are twin scams of emotion.",
      "‘Everyone is getting rich’ is selection bias wearing a tracksuit.",
      "‘This site is official’ — we already told you we aren’t. Others will lie.",
      "Clarity is comfortable with unfinished answers. That’s adult.",
    ],
  },
  {
    slug: "proof-matrix",
    title: "Proof matrix",
    pillar: "belonging",
    summary: "The operating rules that keep this site trustworthy.",
    hook: "Trust is a checklist you can publish.",
    tags: ["trust", "about"],
    related: [
      "why-uk-domain",
      "unofficial-disclaimer",
      "not-financial-advice",
      "phishing-red-flags",
      "join-the-list",
    ],
    body: [
      "UK presence without fake authority. Performance budgets without dashboard theatre. Zero price prophecy.",
      "Every major page should send you deeper into Clarity, Safety, or Belonging — not into a dead end.",
      "If we break these rules, call it out. The pack polices the tone.",
      "This page is the skeptic filter made bookmarkable.",
    ],
  },
  {
    slug: "join-the-list",
    title: "Join the UK list",
    pillar: "belonging",
    summary: "Low-friction updates when we publish useful things — not noise.",
    hook: "Signal only. No carnival barkers.",
    tags: ["funnel", "community"],
    related: [
      "uk-community-pulse",
      "why-uk-domain",
      "first-doge-checklist",
      "phishing-red-flags",
      "proof-matrix",
    
      "creators-and-builders",],
    body: [
      "Use the home page funnel to request the update stream that matches you: explainers, safety, community, or builders.",
      "We show live UK desk availability so you know whether a human is in-hours.",
      "Email requests open your mail client on purpose — fewer dark patterns, more intent.",
      "Belonging scales through useful drops, not daily spam.",
    ],
  },
  {
    slug: "tipping-culture",
    title: "Tipping culture",
    pillar: "belonging",
    summary: "How DOGE tip culture works — and how scammers counterfeit it.",
    hook: "Generosity is the brand. Impersonation is the parasite.",
    tags: ["culture", "tips"],
    related: [
      "culture-and-memes",
      "fake-giveaways",
      "much-wow-lexicon",
      "phishing-red-flags",
      "uk-community-pulse",
    
      "charity-and-causes",
      "dogecoin-tips-irl",],
    body: [
      "Dogecoin’s tip culture taught a generation that micro-generosity can be playful.",
      "Scammers copy the warmth and add a payment demand. Real tips never require you to send first to a stranger’s ‘matching’ address.",
      "If a tip request arrives with urgency, it is not a tip.",
      "Belonging means protecting the generous impulse from becoming an attack surface.",
    ],
  },
  {
    slug: "hardware-wallets",
    title: "Hardware wallets",
    pillar: "safety",
    summary: "When a hardware device is worth it — and when it is theatre.",
    hook: "Cold storage is a tool, not a personality.",
    tags: ["hardware", "custody"],
    related: [
      "self-custody-checklist",
      "seed-phrases",
      "wallets-explained",
      "exchange-vs-wallet",
      "first-doge-checklist",
    
      "multisig-basics",
      "cold-storage-tiers",],
    body: [
      "Hardware wallets keep keys offline for most signing flows. That reduces malware risk for larger balances.",
      "They do not fix bad habits: phishing sites, photographed seeds, or blind trust in ‘setup helpers.’",
      "Buy from official channels. Used devices are a horror genre.",
      "Start with software for learning amounts; graduate hardware when the sleep-at-night number demands it.",
    ],
  },
  {
    slug: "confirmations-explained",
    title: "Confirmations explained",
    pillar: "clarity",
    summary: "Why waits exist, and how many is ‘enough’ for different stakes.",
    hook: "Finality is a gradient, not a gong.",
    tags: ["network", "basics"],
    related: [
      "how-dogecoin-works",
      "fees-and-speed",
      "address-hygiene",
      "first-doge-checklist",
      "common-mistakes",
    
      "network-congestion",],
    body: [
      "Each new block buried on top of your transaction makes reversal harder.",
      "Coffee-money and house-money deserve different patience. Match confirmation depth to consequence.",
      "Exchanges set their own deposit thresholds. Those rules are risk policies, not cosmic law.",
      "If someone demands you treat an unconfirmed tx as sacred settlement, slow down.",
    ],
  },
  {
    slug: "social-engineering",
    title: "Social engineering 101",
    pillar: "safety",
    summary: "How trust is hacked without touching code.",
    hook: "The vulnerability is often kindness.",
    tags: ["scams", "psychology"],
    related: [
      "scam-patterns-uk",
      "support-impersonation",
      "phishing-red-flags",
      "if-you-got-scammed",
      "fake-giveaways",
    ],
    body: [
      "Social engineering scripts borrow authority, fear, romance, or greed — then ask for a small irreversible step.",
      "UK phone and WhatsApp vectors are common. Verify through a second channel you initiate.",
      "Practice saying ‘I’ll call you back on the official number.’ It feels rude. It is adult.",
      "Safety literacy is emotional literacy under pressure.",
    ],
  },
  {
    slug: "dogecoin-history",
    title: "A short Dogecoin history",
    pillar: "clarity",
    summary: "From joke fork to cultural fixture — the arc without mythology overload.",
    hook: "Origin stories explain tone. They do not predict price.",
    tags: ["history", "culture"],
    related: [
      "what-is-dogecoin",
      "is-dogecoin-a-joke",
      "culture-and-memes",
      "dogecoin-vs-bitcoin",
      "why-uk-domain",
    ],
    body: [
      "Dogecoin launched in 2013 as a light-hearted fork culture experiment and somehow refused to die.",
      "Attention cycles came in waves. Each wave onboarded new humans and new predators.",
      "History helps you spot recycled narratives dressed as novelty.",
      "Read it for orientation, not nostalgia investment thesis cosplay.",
    ],
  },
  {
    slug: "meetups-and-irl",
    title: "Meetups and IRL",
    pillar: "belonging",
    summary: "How to gather in the UK without turning into a pitch room.",
    hook: "The best meetup ends with people safer than they arrived.",
    tags: ["uk", "community", "irl"],
    related: [
      "uk-community-pulse",
      "phishing-red-flags",
      "first-doge-checklist",
      "why-uk-domain",
      "tipping-culture",
    
      "community-moderation",
      "dogecoin-tips-irl",
      "uk-meetup-safety",],
    body: [
      "Open with a safety five minutes. Normalise seed hygiene talk like you normalise fire exits.",
      "Avoid on-stage price prophecy. Teach a skill: address verify, wallet backup, scam teardown.",
      "Publish notes afterward so remote UK folks inherit the signal.",
      "Belonging scales when IRL generosity meets online clarity.",
    ],
  },
  {
    slug: "password-and-2fa",
    title: "Passwords and 2FA",
    pillar: "safety",
    summary: "Exchange hygiene that prevents the boring disasters.",
    hook: "Most ‘hacks’ are reused passwords with better marketing.",
    tags: ["opsec", "exchange"],
    related: [
      "exchange-vs-wallet",
      "scam-patterns-uk",
      "support-impersonation",
      "self-custody-checklist",
      "common-mistakes",
    
      "stable-habits",
      "public-wifi-risks",],
    body: [
      "Unique passwords. A manager. App-based or hardware 2FA over SMS when you can.",
      "SIM-swap is a UK-relevant threat. SMS 2FA is better than nothing and worse than app 2FA.",
      "Withdrawal allowlists add friction that saves careers.",
      "Boring security is elite security.",
    ],
  },
  {
    slug: "reading-block-explorers",
    title: "Reading block explorers",
    pillar: "clarity",
    summary: "How to verify a send yourself without trusting a screenshot.",
    hook: "Screenshots lie. Explorers gossip truthfully.",
    tags: ["tools", "network"],
    related: [
      "confirmations-explained",
      "how-dogecoin-works",
      "address-hygiene",
      "fees-and-speed",
      "common-mistakes",
    
      "dust-and-spam",
      "transaction-notes",],
    body: [
      "Paste a txid into a reputable explorer. Confirm amount, addresses, and confirmation count.",
      "Never trust a cropped image from a stranger as proof of payment.",
      "Learn the difference between ‘broadcast’ and ‘confirmed.’",
      "Clarity tools turn anxiety into checkable facts.",
    ],
  },
  {
    slug: "creators-and-builders",
    title: "Creators and builders",
    pillar: "belonging",
    summary: "Making things in the DOGE orbit without extractive hustle energy.",
    hook: "Build for the pack, not the extract.",
    tags: ["builders", "community"],
    related: [
      "uk-community-pulse",
      "join-the-list",
      "culture-and-memes",
      "why-uk-domain",
      "proof-matrix",
    ],
    body: [
      "Tools, explainers, art, and meetup ops all count as building.",
      "Disclose affiliations. Hidden bags plus loud advice is a trust tax.",
      "Ship useful docs. Memes without manuals strand newcomers.",
      "UK builders: document in .co.uk English — dry, clear, kind.",
    ],
  },
  {
    slug: "paper-wallets",
    title: "Paper wallets",
    pillar: "safety",
    summary: "Paper backups: when they help and how they fail.",
    hook: "Analog is not automatically safe.",
    tags: ["custody", "backup"],
    related: [
      "seed-phrases",
      "self-custody-checklist",
      "hardware-wallets",
      "common-mistakes",
      "wallets-explained",
    
      "cold-storage-tiers",],
    body: [
      "Paper backups: when they help and how they fail. This page exists so the graph has another door for that intent.",
      "Pillar alignment: safety. Read it slowly, then follow two related links.",
      "UK frame: keep procedures boring and verify outside DMs.",
      "When in doubt, return to the Safety hub before acting.",
    ],
  },
  {
    slug: "multisig-basics",
    title: "Multisig basics",
    pillar: "safety",
    summary: "Shared control without shared chaos.",
    hook: "One key is a single story.",
    tags: ["custody", "advanced"],
    related: [
      "self-custody-checklist",
      "hardware-wallets",
      "seed-phrases",
      "wallets-explained",
      "exchange-vs-wallet",
    ],
    body: [
      "Shared control without shared chaos. This page exists so the graph has another door for that intent.",
      "Pillar alignment: safety. Read it slowly, then follow two related links.",
      "UK frame: keep procedures boring and verify outside DMs.",
      "When in doubt, return to the Safety hub before acting.",
    ],
  },
  {
    slug: "liquidity-basics",
    title: "Liquidity basics",
    pillar: "clarity",
    summary: "Why the price you see is not always the price you get.",
    hook: "Screens lie politely.",
    tags: ["markets", "basics"],
    related: [
      "uk-buying-basics",
      "fees-and-speed",
      "not-financial-advice",
      "common-mistakes",
      "why-people-buy-doge",
    
      "market-orders-basics",
      "spread-and-slippage",],
    body: [
      "Why the price you see is not always the price you get. This page exists so the graph has another door for that intent.",
      "Pillar alignment: clarity. Read it slowly, then follow two related links.",
      "UK frame: keep procedures boring and verify outside DMs.",
      "When in doubt, return to the Safety hub before acting.",
    ],
  },
  {
    slug: "volatility-psychology",
    title: "Volatility psychology",
    pillar: "belonging",
    summary: "How fear and euphoria hijack good procedures.",
    hook: "Your nervous system is part of the stack.",
    tags: ["psychology", "culture"],
    related: [
      "first-doge-checklist",
      "common-mistakes",
      "not-financial-advice",
      "why-people-buy-doge",
      "social-engineering",
    ],
    body: [
      "How fear and euphoria hijack good procedures. This page exists so the graph has another door for that intent.",
      "Pillar alignment: belonging. Read it slowly, then follow two related links.",
      "UK frame: keep procedures boring and verify outside DMs.",
      "When in doubt, return to the Safety hub before acting.",
    ],
  },
  {
    slug: "charity-and-causes",
    title: "Charity and causes",
    pillar: "belonging",
    summary: "DOGE charity energy — verify before you donate.",
    hook: "Kindness attracts counterfeits.",
    tags: ["culture", "trust"],
    related: [
      "tipping-culture",
      "fake-giveaways",
      "phishing-red-flags",
      "culture-and-memes",
      "uk-community-pulse",
    ],
    body: [
      "DOGE charity energy — verify before you donate. This page exists so the graph has another door for that intent.",
      "Pillar alignment: belonging. Read it slowly, then follow two related links.",
      "UK frame: keep procedures boring and verify outside DMs.",
      "When in doubt, return to the Safety hub before acting.",
    ],
  },
  {
    slug: "nodes-and-clients",
    title: "Nodes and clients",
    pillar: "clarity",
    summary: "What running software for the network actually means.",
    hook: "Participation has layers.",
    tags: ["network", "software"],
    related: [
      "how-dogecoin-works",
      "mining-and-security",
      "reading-block-explorers",
      "what-is-dogecoin",
      "confirmations-explained",
    
      "open-source-trust",],
    body: [
      "What running software for the network actually means. This page exists so the graph has another door for that intent.",
      "Pillar alignment: clarity. Read it slowly, then follow two related links.",
      "UK frame: keep procedures boring and verify outside DMs.",
      "When in doubt, return to the Safety hub before acting.",
    ],
  },
  {
    slug: "mobile-wallet-hygiene",
    title: "Mobile wallet hygiene",
    pillar: "safety",
    summary: "Phones are convenient attack surfaces.",
    hook: "Your pocket computer is a fortress only if you treat it like one.",
    tags: ["mobile", "opsec"],
    related: [
      "wallets-explained",
      "seed-phrases",
      "phishing-red-flags",
      "password-and-2fa",
      "self-custody-checklist",
    
      "public-wifi-risks",],
    body: [
      "Phones are convenient attack surfaces. This page exists so the graph has another door for that intent.",
      "Pillar alignment: safety. Read it slowly, then follow two related links.",
      "UK frame: keep procedures boring and verify outside DMs.",
      "When in doubt, return to the Safety hub before acting.",
    ],
  },
  {
    slug: "uk-tax-mindset",
    title: "UK tax mindset",
    pillar: "clarity",
    summary: "Record-keeping mindset — not advice, just future-you kindness.",
    hook: "HMRC does not accept vibes.",
    tags: ["uk", "records"],
    related: [
      "uk-buying-basics",
      "not-financial-advice",
      "exchange-vs-wallet",
      "first-doge-checklist",
      "why-uk-domain",
    
      "transaction-notes",],
    body: [
      "Record-keeping mindset — not advice, just future-you kindness. This page exists so the graph has another door for that intent.",
      "Pillar alignment: clarity. Read it slowly, then follow two related links.",
      "UK frame: keep procedures boring and verify outside DMs.",
      "When in doubt, return to the Safety hub before acting.",
    ],
  },
  {
    slug: "influencer-disclosures",
    title: "Influencer disclosures",
    pillar: "belonging",
    summary: "How to read paid enthusiasm without becoming the exit liquidity.",
    hook: "Charisma is not due diligence.",
    tags: ["culture", "media"],
    related: [
      "why-people-buy-doge",
      "not-financial-advice",
      "social-engineering",
      "fake-giveaways",
      "proof-matrix",
    ],
    body: [
      "How to read paid enthusiasm without becoming the exit liquidity. This page exists so the graph has another door for that intent.",
      "Pillar alignment: belonging. Read it slowly, then follow two related links.",
      "UK frame: keep procedures boring and verify outside DMs.",
      "When in doubt, return to the Safety hub before acting.",
    ],
  },
  {
    slug: "test-transactions",
    title: "Test transactions",
    pillar: "safety",
    summary: "The tiny send that prevents the huge regret.",
    hook: "Ritual beats bravado.",
    tags: ["checklist", "opsec"],
    related: [
      "address-hygiene",
      "fees-and-speed",
      "first-doge-checklist",
      "common-mistakes",
      "confirmations-explained",
    
      "qr-code-hygiene",],
    body: [
      "The tiny send that prevents the huge regret. This page exists so the graph has another door for that intent.",
      "Pillar alignment: safety. Read it slowly, then follow two related links.",
      "UK frame: keep procedures boring and verify outside DMs.",
      "When in doubt, return to the Safety hub before acting.",
    ],
  },
  {
    slug: "forks-and-clones",
    title: "Forks and clones",
    pillar: "clarity",
    summary: "Lookalike coins and why names are not destiny.",
    hook: "Branding is cheap. Networks are not.",
    tags: ["basics", "risk"],
    related: [
      "what-is-dogecoin",
      "dogecoin-vs-bitcoin",
      "phishing-red-flags",
      "myths-to-ignore",
      "doge-glossary",
    ],
    body: [
      "Lookalike coins and why names are not destiny. This page exists so the graph has another door for that intent.",
      "Pillar alignment: clarity. Read it slowly, then follow two related links.",
      "UK frame: keep procedures boring and verify outside DMs.",
      "When in doubt, return to the Safety hub before acting.",
    ],
  },
  {
    slug: "community-moderation",
    title: "Community moderation",
    pillar: "belonging",
    summary: "Keeping UK spaces kind without becoming a cult.",
    hook: "Boundaries are hospitality.",
    tags: ["community", "uk"],
    related: [
      "uk-community-pulse",
      "meetups-and-irl",
      "phishing-red-flags",
      "unofficial-disclaimer",
      "creators-and-builders",
    
      "uk-meetup-safety",
      "moderation-playbook",],
    body: [
      "Keeping UK spaces kind without becoming a cult. This page exists so the graph has another door for that intent.",
      "Pillar alignment: belonging. Read it slowly, then follow two related links.",
      "UK frame: keep procedures boring and verify outside DMs.",
      "When in doubt, return to the Safety hub before acting.",
    ],
  },
  {
    slug: "cold-storage-tiers",
    title: "Cold storage tiers",
    pillar: "safety",
    summary: "Match custody tier to amount and life chaos.",
    hook: "Not everything needs a vault. Some things do.",
    tags: ["custody", "tiers"],
    related: [
      "hardware-wallets",
      "paper-wallets",
      "self-custody-checklist",
      "exchange-vs-wallet",
      "first-doge-checklist",
    
      "hot-wallet-limits",],
    body: [
      "Match custody tier to amount and life chaos. This page exists so the graph has another door for that intent.",
      "Pillar alignment: safety. Read it slowly, then follow two related links.",
      "UK frame: keep procedures boring and verify outside DMs.",
      "When in doubt, return to the Safety hub before acting.",
    ],
  },
  {
    slug: "meme-literacy",
    title: "Meme literacy",
    pillar: "belonging",
    summary: "Reading jokes so you do not fund them blindly.",
    hook: "Laughter is onboarding — and camouflage.",
    tags: ["culture", "literacy"],
    related: [
      "culture-and-memes",
      "much-wow-lexicon",
      "fake-giveaways",
      "is-dogecoin-a-joke",
      "tipping-culture",
    ],
    body: [
      "Reading jokes so you do not fund them blindly. This page exists so the graph has another door for that intent.",
      "Pillar alignment: belonging. Read it slowly, then follow two related links.",
      "UK frame: keep procedures boring and verify outside DMs.",
      "When in doubt, return to the Safety hub before acting.",
    ],
  },
  {
    slug: "network-congestion",
    title: "Network congestion",
    pillar: "clarity",
    summary: "What busy moments feel like and how to respond.",
    hook: "Patience is a fee strategy.",
    tags: ["fees", "network"],
    related: [
      "fees-and-speed",
      "confirmations-explained",
      "how-dogecoin-works",
      "reading-block-explorers",
      "common-mistakes",
    ],
    body: [
      "What busy moments feel like and how to respond. This page exists so the graph has another door for that intent.",
      "Pillar alignment: clarity. Read it slowly, then follow two related links.",
      "UK frame: keep procedures boring and verify outside DMs.",
      "When in doubt, return to the Safety hub before acting.",
    ],
  },
  {
    slug: "family-and-inheritance",
    title: "Family and inheritance",
    pillar: "safety",
    summary: "Harsh topic, practical notes for shared reality.",
    hook: "Secrets that die with you are not a plan.",
    tags: ["custody", "life"],
    related: [
      "seed-phrases",
      "self-custody-checklist",
      "multisig-basics",
      "hardware-wallets",
      "not-financial-advice",
    ],
    body: [
      "Harsh topic, practical notes for shared reality. This page exists so the graph has another door for that intent.",
      "Pillar alignment: safety. Read it slowly, then follow two related links.",
      "UK frame: keep procedures boring and verify outside DMs.",
      "When in doubt, return to the Safety hub before acting.",
    ],
  },
  {
    slug: "onboarding-a-friend",
    title: "Onboarding a friend",
    pillar: "belonging",
    summary: "Teach DOGE without dunking or dumping risk on them.",
    hook: "The best flex is someone else staying safe.",
    tags: ["community", "teaching"],
    related: [
      "first-doge-checklist",
      "phishing-red-flags",
      "what-is-dogecoin",
      "meetups-and-irl",
      "tipping-culture",
    ],
    body: [
      "Teach DOGE without dunking or dumping risk on them. This page exists so the graph has another door for that intent.",
      "Pillar alignment: belonging. Read it slowly, then follow two related links.",
      "UK frame: keep procedures boring and verify outside DMs.",
      "When in doubt, return to the Safety hub before acting.",
    ],
  },
  {
    slug: "stable-habits",
    title: "Stable habits",
    pillar: "safety",
    summary: "Daily/weekly rituals that reduce unforced errors.",
    hook: "Discipline is a safety feature.",
    tags: ["habits", "checklist"],
    related: [
      "first-doge-checklist",
      "password-and-2fa",
      "address-hygiene",
      "volatility-psychology",
      "common-mistakes",
    ],
    body: [
      "Daily/weekly rituals that reduce unforced errors. This page exists so the graph has another door for that intent.",
      "Pillar alignment: safety. Read it slowly, then follow two related links.",
      "UK frame: keep procedures boring and verify outside DMs.",
      "When in doubt, return to the Safety hub before acting.",
    ],
  },
  {
    slug: "open-source-trust",
    title: "Open source trust",
    pillar: "clarity",
    summary: "How to think about software trust without becoming a auditor cosplay.",
    hook: "Verify what you can. Contain what you cannot.",
    tags: ["software", "trust"],
    related: [
      "wallets-explained",
      "nodes-and-clients",
      "phishing-red-flags",
      "self-custody-checklist",
      "proof-matrix",
    ],
    body: [
      "How to think about software trust without becoming a auditor cosplay. This page exists so the graph has another door for that intent.",
      "Pillar alignment: clarity. Read it slowly, then follow two related links.",
      "UK frame: keep procedures boring and verify outside DMs.",
      "When in doubt, return to the Safety hub before acting.",
    ],
  },
  {
    slug: "uk-search-intent",
    title: "UK search intent",
    pillar: "belonging",
    summary: "Why people type dogecoin.co.uk — and how we answer.",
    hook: "The query is an emotion with keywords.",
    tags: ["uk", "seo", "psychology"],
    related: [
      "why-uk-domain",
      "what-is-dogecoin",
      "phishing-red-flags",
      "join-the-list",
      "proof-matrix",
    ],
    body: [
      "Why people type dogecoin.co.uk — and how we answer. This page exists so the graph has another door for that intent.",
      "Pillar alignment: belonging. Read it slowly, then follow two related links.",
      "UK frame: keep procedures boring and verify outside DMs.",
      "When in doubt, return to the Safety hub before acting.",
    ],
  },
  {
    slug: "dust-and-spam",
    title: "Dust and spam",
    pillar: "clarity",
    summary: "Tiny unexpected amounts and why they appear.",
    hook: "Not every surprise is a gift.",
    tags: ["network", "privacy"],
    related: [
      "address-hygiene",
      "reading-block-explorers",
      "phishing-red-flags",
      "wallets-explained",
      "common-mistakes",
    ],
    body: [
      "Tiny unexpected amounts and why they appear. This page exists so the graph has another door for that intent.",
      "Pillar alignment: clarity. Read it slowly, then follow two related links.",
      "UK frame: keep procedures boring and verify outside DMs.",
      "When in doubt, return to the Safety hub before acting.",
    ],
  },
  {
    slug: "hot-wallet-limits",
    title: "Hot wallet limits",
    pillar: "safety",
    summary: "How much to keep online vs cold — a practical ceiling.",
    hook: "Convenience has a balance cap.",
    tags: ["custody", "limits"],
    related: [
      "cold-storage-tiers",
      "wallets-explained",
      "self-custody-checklist",
      "first-doge-checklist",
      "stable-habits",
    ],
    body: [
      "Hot wallets are for spending and learning amounts. Cold storage is for sleep-at-night amounts.",
      "Pick a personal ceiling you can lose without wrecking your month — then enforce it.",
      "When the hot balance creeps up ‘temporarily,’ schedule the move before the next hype wave.",
      "Safety is a limit you honour when markets are loud.",
    ],
  },
  {
    slug: "qr-code-hygiene",
    title: "QR code hygiene",
    pillar: "safety",
    summary: "Scanning safely without feeding malware or wrong addresses.",
    hook: "A QR is just text wearing sunglasses.",
    tags: ["opsec", "addresses"],
    related: [
      "address-hygiene",
      "test-transactions",
      "phishing-red-flags",
      "mobile-wallet-hygiene",
      "common-mistakes",
    ],
    body: [
      "Read the decoded address before you confirm. Stickers and overlays exist in the wild.",
      "Prefer showing your receive QR from your own wallet — not a PDF someone emailed.",
      "For large moves, still do a dust test after scanning.",
      "QR convenience dies the moment you stop verifying.",
    ],
  },
  {
    slug: "public-wifi-risks",
    title: "Public Wi‑Fi risks",
    pillar: "safety",
    summary: "Cafés, airports, and the quiet ways sessions get stolen.",
    hook: "Free Wi‑Fi is rarely free of intent.",
    tags: ["opsec", "mobile"],
    related: [
      "mobile-wallet-hygiene",
      "password-and-2fa",
      "phishing-red-flags",
      "stable-habits",
      "support-impersonation",
    ],
    body: [
      "Avoid wallet ops on open networks when you can. Use trusted mobile data for signing moments.",
      "Captive portals are phishing theatres. Type known URLs yourself.",
      "VPN helps some threats and none of social engineering.",
      "If you must act on public Wi‑Fi, keep amounts tiny and eyes open.",
    ],
  },
  {
    slug: "browser-extension-risk",
    title: "Browser extension risk",
    pillar: "safety",
    summary: "Wallet extensions: power tools with sharp edges.",
    hook: "If it can sign, it can also steal.",
    tags: ["wallets", "browser"],
    related: [
      "wallets-explained",
      "phishing-red-flags",
      "open-source-trust",
      "seed-phrases",
      "hot-wallet-limits",
    ],
    body: [
      "Install only from sources you typed. Fake extensions clone icons for a living.",
      "Lock the extension when idle. Review connected sites periodically.",
      "A malicious page plus a confused click is enough — slow down on connect prompts.",
      "Serious balances do not live in the browser long-term.",
    ],
  },
  {
    slug: "backup-drill",
    title: "Backup drill",
    pillar: "safety",
    summary: "Practice restoring a wallet before you need to.",
    hook: "Untested backups are fan fiction.",
    tags: ["custody", "checklist"],
    related: [
      "seed-phrases",
      "self-custody-checklist",
      "hardware-wallets",
      "first-doge-checklist",
      "stable-habits",
    ],
    body: [
      "Fund a tiny wallet, back it up, wipe the device path, restore, and confirm the dust is there.",
      "Do this before the balance is emotionally expensive.",
      "Note how long it took and where you got stuck — fix the process, not just the mood.",
      "A drill turns panic into muscle memory.",
    ],
  },
  {
    slug: "transaction-notes",
    title: "Transaction notes",
    pillar: "clarity",
    summary: "Labelling sends so future-you knows what happened.",
    hook: "Memory is not a ledger.",
    tags: ["habits", "records"],
    related: [
      "uk-tax-mindset",
      "reading-block-explorers",
      "first-doge-checklist",
      "stable-habits",
      "address-hygiene",
    ],
    body: [
      "Keep a private note of date, amount, counterparty label, and why — not on the public chain.",
      "UK angle: good notes reduce future stress. This is not tax advice.",
      "Screenshots alone rot. Structured notes survive.",
      "Clarity compounds when your history is readable.",
    ],
  },
  {
    slug: "utxo-mental-model",
    title: "UTXO mental model",
    pillar: "clarity",
    summary: "Coins as notes, not a single bank balance number.",
    hook: "Understanding inputs prevents weird fee surprises.",
    tags: ["network", "basics"],
    related: [
      "how-dogecoin-works",
      "fees-and-speed",
      "reading-block-explorers",
      "dust-and-spam",
      "confirmations-explained",
    ],
    body: [
      "Many cryptocurrencies track unspent outputs. Your ‘balance’ is the sum of notes you can spend.",
      "Sending may consume multiple notes and create change — explorers make this visible.",
      "Dust and spam interact with this model; that’s why address hygiene matters.",
      "You do not need to be an engineer — just stop expecting a bank UI under the hood.",
    ],
  },
  {
    slug: "market-orders-basics",
    title: "Market orders basics",
    pillar: "clarity",
    summary: "Buy/sell buttons without pretending it’s advice.",
    hook: "Execution mechanics ≠ destiny.",
    tags: ["markets", "uk"],
    related: [
      "uk-buying-basics",
      "liquidity-basics",
      "not-financial-advice",
      "fees-and-speed",
      "volatility-psychology",
    
      "spread-and-slippage",],
    body: [
      "A market order prioritises fill speed over exact price. Spreads and depth matter.",
      "During chaos, the fill can surprise you. Size down or wait.",
      "This page explains mechanics, not whether you should trade.",
      "If urgency is emotional, step away before you click.",
    ],
  },
  {
    slug: "spread-and-slippage",
    title: "Spread and slippage",
    pillar: "clarity",
    summary: "The quiet cost between the price you saw and the fill you got.",
    hook: "Screenshots are optimistic.",
    tags: ["markets", "fees"],
    related: [
      "liquidity-basics",
      "market-orders-basics",
      "uk-buying-basics",
      "fees-and-speed",
      "common-mistakes",
    ],
    body: [
      "Spread is the gap between buy and sell quotes. Slippage is movement while your order executes.",
      "Thin books and big size make both worse.",
      "Not advice — just the maths of impatience.",
      "Compare total cost, not the headline ticker alone.",
    ],
  },
  {
    slug: "dogecoin-tips-irl",
    title: "DOGE tips IRL",
    pillar: "belonging",
    summary: "Tipping in person without turning it into a scam demo.",
    hook: "Warmth needs a verify step.",
    tags: ["culture", "irl"],
    related: [
      "tipping-culture",
      "qr-code-hygiene",
      "meetups-and-irl",
      "test-transactions",
      "address-hygiene",
    ],
    body: [
      "Show a receive address from your own wallet. Confirm on both screens.",
      "Start tiny. Celebrate the ritual more than the amount.",
      "Never ‘match’ a tip to a stranger’s urgent address.",
      "IRL kindness plus verify steps is the UK brand of belonging.",
    ],
  },
  {
    slug: "uk-meetup-safety",
    title: "UK meetup safety",
    pillar: "belonging",
    summary: "Run or attend a meetup without becoming a honeypot.",
    hook: "Hospitality includes exits and boundaries.",
    tags: ["uk", "irl"],
    related: [
      "meetups-and-irl",
      "community-moderation",
      "phishing-red-flags",
      "onboarding-a-friend",
      "uk-community-pulse",
    ],
    body: [
      "Public venue, clear end time, no seed phrases on stage, no pressure to install apps on the spot.",
      "Announce that support never DMs first — say it out loud every time.",
      "Pair newcomers with a buddy for their first questions.",
      "A safe meetup grows the graph offline.",
    ],
  },
  {
    slug: "moderation-playbook",
    title: "Moderation playbook",
    pillar: "belonging",
    summary: "Kick spam, keep kindness, refuse fake support theatre.",
    hook: "Tone is infrastructure.",
    tags: ["community", "trust"],
    related: [
      "community-moderation",
      "support-impersonation",
      "fake-giveaways",
      "uk-community-pulse",
      "proof-matrix",
    ],
    body: [
      "Pin rules: no price calls as gospel, no seed requests, no ‘support’ in DMs.",
      "Remove giveaway bots quickly — engagement is their oxygen.",
      "Document patterns so new mods inherit judgement, not vibes alone.",
      "Belonging scales when moderation is calm and consistent.",
    ],
  },
];
