import type { PageNode } from "./types";

/** Visitor-facing guide library. Every page links out via `related`. */
export const catalog: PageNode[] = [
  {
    slug: "what-is-dogecoin",
    title: "What is Dogecoin?",
    pillar: "clarity",
    hub: true,
    summary: "A plain-English map of DOGE: coin, culture, and why it still matters.",
    hook: "You already know the meme. Here’s the machine underneath it.",
    tags: ["basics", "intro", "doge"],
    related: [
      "how-dogecoin-works",
      "dogecoin-vs-bitcoin",
      "doge-glossary",
      "why-uk-domain",
      "is-dogecoin-a-joke",
    
      "tipping-culture",
      "dogecoin-history",
      "forks-and-clones",
      "uk-search-intent",
      "newcomer-script",
      "what-dogecoin-is-not",
      "reading-charts-calmly",
      "meme-coins-vs-dogecoin",
      "dogecoin-for-parents",
    ],
    body: [
      "Dogecoin is a cryptocurrency that started as a joke and became a living culture. The coin moves on a public network; the meme moves through people.",
      "You do not need a finance degree to hold a mental model. DOGE is digital cash with a community that prizes humour, tips, and approachability over gatekeeping.",
      "This site exists because UK searchers keep arriving with the same quiet question: what is this, really — and how do I engage without getting burned?",
      "Clarity first. Then safety. Then belonging. That order is intentional.",
    ],
  },
  {
    slug: "how-dogecoin-works",
    title: "How Dogecoin works",
    pillar: "clarity",
    summary: "Blocks, wallets, fees, and confirmations — without the textbook fog.",
    hook: "If you can follow a bank transfer, you can follow a DOGE send.",
    tags: ["basics", "network", "wallets"],
    related: [
      "what-is-dogecoin",
      "wallets-explained",
      "fees-and-speed",
      "mining-and-security",
      "seed-phrases",
    
      "confirmations-explained",
      "reading-block-explorers",
      "nodes-and-clients",
      "utxo-mental-model",],
    body: [
      "Dogecoin transactions are messages broadcast to a peer-to-peer network. Miners (and the wider network) race to order those messages into blocks.",
      "Your wallet does not ‘store coins like a purse.’ It stores keys that prove you can move balances recorded on the public ledger.",
      "A send is final after enough confirmations. Fees pay for inclusion priority. Speed is usually fine for everyday amounts; huge transfers deserve extra caution.",
      "When something feels magical, zoom out: it’s cryptography + incentives + open software — not vibes alone.",
    ],
  },
  {
    slug: "dogecoin-vs-bitcoin",
    title: "Dogecoin vs Bitcoin",
    pillar: "clarity",
    summary: "Same family tree, different temperament. Compare without tribal warfare.",
    hook: "Bitcoin is the cathedral. Dogecoin is the festival outside.",
    tags: ["compare", "bitcoin", "basics"],
    related: [
      "what-is-dogecoin",
      "inflation-and-supply",
      "is-dogecoin-a-joke",
      "why-people-buy-doge",
      "culture-and-memes",
    
      "forks-and-clones",],
    body: [
      "Both are proof-of-work cryptocurrencies. Bitcoin optimises for scarcity narrative and settlement gravity. Dogecoin optimises for approachability and cultural velocity.",
      "Supply design differs. That is not a moral verdict — it is a design choice with trade-offs for fees, miner incentives, and long-term story.",
      "If someone forces you to ‘pick a side,’ leave the thread. Useful comparison is about use-cases, not identity combat.",
      "For UK newcomers: learn Bitcoin’s security lessons, borrow Dogecoin’s human tone, and ignore the purity contests.",
    ],
  },
  {
    slug: "doge-glossary",
    title: "DOGE glossary",
    pillar: "clarity",
    summary: "The words people throw around — defined like a human wrote them.",
    hook: "Jargon is a velvet rope. Cut it.",
    tags: ["glossary", "basics"],
    related: [
      "what-is-dogecoin",
      "wallets-explained",
      "seed-phrases",
      "phishing-red-flags",
      "fees-and-speed",
    ],
    body: [
      "Wallet: software or hardware that manages keys. Exchange account: a company balance that is not the same as self-custody.",
      "Seed phrase: the master backup words. Anyone with them can empty the wallet. Never type them into a website.",
      "Gas/fees: payment to get your transaction included. DOGE fees are usually small, but ‘usually’ is not a promise.",
      "HODL, FOMO, rekt, rug: culture words. Learn them so scammers cannot hide behind slang.",
    ],
  },
  {
    slug: "wallets-explained",
    title: "Wallets explained (UK)",
    pillar: "clarity",
    summary: "Custodial vs self-custody, phone vs hardware, and what ‘not your keys’ means.",
    hook: "The wallet question is really a trust question.",
    tags: ["wallets", "custody", "uk"],
    related: [
      "seed-phrases",
      "self-custody-checklist",
      "exchange-vs-wallet",
      "how-dogecoin-works",
      "first-doge-checklist",
    
      "hardware-wallets",
      "mobile-wallet-hygiene",
      "open-source-trust",
      "hot-wallet-limits",
      "browser-extension-risk",],
    body: [
      "An exchange wallet is convenient and fragile: the company holds the keys. Fine for tiny experiments; poor as a life vault.",
      "A self-custody wallet puts responsibility on you. That is freedom and liability in the same box.",
      "Hardware wallets reduce malware risk for larger balances. Phone wallets are fine for learning amounts if you back up the seed offline.",
      "UK angle: keep records for your own sanity. This is not tax advice — it is future-you protection.",
    ],
  },
  {
    slug: "fees-and-speed",
    title: "Fees and speed",
    pillar: "clarity",
    summary: "What you pay, what you wait for, and when to slow down on purpose.",
    hook: "Cheap and fast is great — until you send to the wrong address.",
    tags: ["fees", "network"],
    related: [
      "how-dogecoin-works",
      "first-doge-checklist",
      "address-hygiene",
      "wallets-explained",
      "common-mistakes",
    
      "liquidity-basics",
      "test-transactions",
      "network-congestion",
      "utxo-mental-model",],
    body: [
      "Network fees buy priority. During quiet periods they are negligible. During chaos, patience beats panic.",
      "Confirmation time is not ‘instant like Apple Pay.’ Plan for minutes, not milliseconds, when it matters.",
      "Test with a tiny send before a large one. That single habit prevents more pain than any thread tip.",
      "If a stranger rushes you to skip the test send, that stranger is the risk.",
    ],
  },
  {
    slug: "mining-and-security",
    title: "Mining and network security",
    pillar: "clarity",
    summary: "Why miners exist, what they secure, and what they don’t promise.",
    hook: "Security is an incentive machine, not a vibe.",
    tags: ["mining", "security"],
    related: [
      "how-dogecoin-works",
      "inflation-and-supply",
      "dogecoin-vs-bitcoin",
      "what-is-dogecoin",
      "myths-to-ignore",
    
      "nodes-and-clients",],
    body: [
      "Miners expend energy to propose blocks. The network’s rules decide which history wins.",
      "Mining does not guarantee your personal OPSEC. It secures consensus, not your seed phrase hygiene.",
      "Hashrate stories are interesting. They are not investment theses by themselves.",
      "If you only remember one line: the chain can be robust while your habits are not.",
    ],
  },
  {
    slug: "inflation-and-supply",
    title: "Inflation and supply",
    pillar: "clarity",
    summary: "Dogecoin’s issuance model in calm language — trade-offs included.",
    hook: "‘Infinite’ is a meme. Issuance is a schedule.",
    tags: ["supply", "economics"],
    related: [
      "dogecoin-vs-bitcoin",
      "why-people-buy-doge",
      "myths-to-ignore",
      "what-is-dogecoin",
      "mining-and-security",
    ],
    body: [
      "Dogecoin continues to issue new coins over time. That design funds security and keeps the monetary story different from hard-cap maximalism.",
      "Whether that is ‘good’ depends on what you want money-like assets to do. There is no universal answer.",
      "Beware charts that treat issuance as destiny. Culture, liquidity, and attention also move price — and price is not this site’s product.",
      "Clarity means naming trade-offs out loud instead of selling certainty.",
    ],
  },
  {
    slug: "is-dogecoin-a-joke",
    title: "Is Dogecoin a joke?",
    pillar: "belonging",
    summary: "Yes — and also a serious network used by real humans. Both can be true.",
    hook: "The joke is the onboarding. The network is the machinery.",
    tags: ["culture", "myths"],
    related: [
      "culture-and-memes",
      "what-is-dogecoin",
      "why-people-buy-doge",
      "myths-to-ignore",
      "uk-community-pulse",
    
      "dogecoin-history",],
    body: [
      "Dogecoin began as satire. That origin is a feature: it lowers the intimidation tax that keeps people out of crypto.",
      "Treating it only as a joke can make you careless. Treating it only as sacred can make you cruel. Aim for warm precision.",
      "UK conversations often split between ‘it’s funny’ and ‘it’s dangerous.’ This site holds both truths without the shouting.",
      "Belonging here means you can laugh and still check the address twice.",
    ],
  },
  {
    slug: "culture-and-memes",
    title: "Culture and memes",
    pillar: "belonging",
    summary: "Shiba energy, tip culture, and why kindness became a brand asset.",
    hook: "Memes are the user interface for emotion.",
    tags: ["culture", "community"],
    related: [
      "is-dogecoin-a-joke",
      "uk-community-pulse",
      "much-wow-lexicon",
      "why-uk-domain",
      "what-is-dogecoin",
    
      "tipping-culture",
      "meme-literacy",],
    body: [
      "Dogecoin culture rewards tipping, charity bits, and not taking yourself too seriously — until money is on the line.",
      "Memes compress belonging. They also compress scams: fake giveaways wear the same costume.",
      "If a meme demands urgency, verify outside the meme. Fun is not a deadline.",
      "This pillar exists so newcomers feel welcomed without being softened up for fraud.",
    ],
  },
  {
    slug: "why-uk-domain",
    title: "Why dogecoin.co.uk exists",
    pillar: "belonging",
    hub: true,
    summary: "A UK front door: local signal, unofficial stance, calm tone.",
    hook: "People trust a postcode vibe before they trust a whitepaper.",
    tags: ["uk", "about", "trust"],
    related: [
      "unofficial-disclaimer",
      "uk-community-pulse",
      "what-is-dogecoin",
      "phishing-red-flags",
      "first-doge-checklist",
    
      "uk-search-intent",],
    body: [
      "dogecoin.co.uk is an unofficial community presence. It is not the Dogecoin Foundation and not a financial adviser.",
      "The `.co.uk` signal answers a quiet visitor question: ‘is there a local, sane explanation?’ Yes — start here.",
      "We refuse price prophecy. We publish checklists, explainers, and culture notes you can actually use.",
      "If you only remember one sentence: warmth without hype is the brand.",
    ],
  },
  {
    slug: "unofficial-disclaimer",
    title: "Unofficial — on purpose",
    pillar: "belonging",
    summary: "Clear boundaries build trust faster than borrowed authority.",
    hook: "Saying what we are not is a feature.",
    tags: ["trust", "legal", "uk"],
    related: [
      "why-uk-domain",
      "not-financial-advice",
      "phishing-red-flags",
      "uk-community-pulse",
      "proof-matrix",
    ],
    body: [
      "This site is community-built and unofficial. That honesty is deliberate.",
      "Borrowed logos and fake ‘official support’ are classic scam costumes. We won’t wear them.",
      "When in doubt, verify claims through primary sources and slow down.",
      "Belonging includes protecting the pack from impostors — including us, if we ever sound off.",
    ],
  },
  {
    slug: "not-financial-advice",
    title: "Not financial advice",
    pillar: "safety",
    summary: "Education is not a recommendation to buy, sell, or hold.",
    hook: "If it sounds like a tip dressed as destiny, walk away.",
    tags: ["safety", "disclaimer"],
    related: [
      "unofficial-disclaimer",
      "why-people-buy-doge",
      "common-mistakes",
      "scam-patterns-uk",
      "first-doge-checklist",
    
      "uk-tax-mindset",
      "influencer-disclosures",],
    body: [
      "Nothing on dogecoin.co.uk is financial, tax, or legal advice. Crypto assets can go to zero.",
      "We explain mechanics and risks so you can think. We do not tell you what to do with money.",
      "If a page ever feels like pressure, treat that feeling as a warning light.",
      "Safety starts with refusing fake certainty.",
    ],
  },
  {
    slug: "phishing-red-flags",
    title: "Phishing red flags",
    pillar: "safety",
    hub: true,
    summary: "The patterns that empty wallets — spotted early.",
    hook: "Urgency is the scam’s favourite font.",
    tags: ["phishing", "scams", "safety"],
    related: [
      "scam-patterns-uk",
      "seed-phrases",
      "fake-giveaways",
      "support-impersonation",
      "address-hygiene",
    
      "onboarding-a-friend",
      "browser-extension-risk",
      "address-poisoning",
      "confirm-before-connect",
      "avoiding-urgency-traps",
      "seed-phrase-never-share",
      "bookmark-hygiene",
    ],
    body: [
      "Nobody legitimate needs your seed phrase. Not support. Not a ‘sync’ page. Not a DM.",
      "Lookalike domains, fake wallet connect prompts, and ‘verification’ deadlines are industrial-scale traps.",
      "UK twist: SMS and email impersonating banks or exchanges spike during market chaos.",
      "When adrenaline rises, open a fresh bookmark to the real site — never the link in the message.",
    ],
  },
  {
    slug: "scam-patterns-uk",
    title: "Scam patterns in the UK",
    pillar: "safety",
    summary: "Local flavours of fraud: romance, investment, and ‘recovery’ cons.",
    hook: "The accent changes. The script doesn’t.",
    tags: ["scams", "uk", "safety"],
    related: [
      "phishing-red-flags",
      "fake-giveaways",
      "support-impersonation",
      "if-you-got-scammed",
      "self-custody-checklist",
    
      "social-engineering",],
    body: [
      "Investment scams promise guaranteed returns and a friendly mentor. Guaranteed returns in crypto are fiction.",
      "Recovery scams arrive after the first loss: ‘specialists’ who need fees to unlock funds. That is round two.",
      "Romance and social engineering use loneliness as an attack surface. Slow relationships beat fast wires.",
      "Report, document, and do not pay ‘unlock’ fees. Pride recovers slower than money — protect both.",
    ],
  },
  {
    slug: "seed-phrases",
    title: "Seed phrases",
    pillar: "safety",
    summary: "The master key: offline, boring, never photographed into the cloud.",
    hook: "If it’s typed into a website, it’s already compromised.",
    tags: ["seed", "custody", "safety"],
    related: [
      "self-custody-checklist",
      "wallets-explained",
      "phishing-red-flags",
      "common-mistakes",
      "first-doge-checklist",
    
      "paper-wallets",
      "mobile-wallet-hygiene",
      "family-and-inheritance",
      "backup-drill",
      "recovery-phrase-storage",
      "seed-phrase-never-share",
      "hardware-wallet-first-hour",
    ],
    body: [
      "A seed phrase recreates your wallet. Treat it like the deed to a house written on paper.",
      "Write it offline. Store it where thieves and flatmates can’t casually find it. Consider metal backups for serious amounts.",
      "Never enter a seed to ‘fix,’ ‘claim,’ or ‘stop a penalty.’ Those words are theatre.",
      "If you already typed a seed into a site, move funds to a fresh wallet immediately — then retire the old one.",
    ],
  },
  {
    slug: "self-custody-checklist",
    title: "Self-custody checklist",
    pillar: "safety",
    summary: "A practical pre-flight before you hold your own keys.",
    hook: "Freedom without a checklist is cosplay.",
    tags: ["checklist", "custody"],
    related: [
      "seed-phrases",
      "wallets-explained",
      "exchange-vs-wallet",
      "address-hygiene",
      "first-doge-checklist",
    
      "paper-wallets",
      "multisig-basics",
      "family-and-inheritance",
      "backup-drill",],
    body: [
      "Download wallets from official sources you typed yourself. Verify you’re not in an app-store clone.",
      "Back up the seed before you fund the wallet. Test recovery on a spare device with dust amounts.",
      "Enable device passcodes and OS updates. Boring hygiene beats clever setups.",
      "Separate ‘learning money’ from ‘serious money.’ Different wallets, different emotional stakes.",
    ],
  },
  {
    slug: "exchange-vs-wallet",
    title: "Exchange vs wallet",
    pillar: "clarity",
    summary: "Convenience accounts versus keys you control — choose knowingly.",
    hook: "Both can be right. Confusion is what’s expensive.",
    tags: ["exchange", "wallets"],
    related: [
      "wallets-explained",
      "self-custody-checklist",
      "first-doge-checklist",
      "uk-buying-basics",
      "common-mistakes",
    
      "password-and-2fa",
      "exchange-outages",
      "withdrawal-allowlists",],
    body: [
      "Exchanges are on-ramps. They are also honeypots: large targets with human processes and outages.",
      "Self-custody removes company risk and adds personal responsibility risk. Pick consciously.",
      "A sane UK path for many beginners: buy small on a reputable venue, withdraw a learning amount to a wallet, practice sends.",
      "Leaving everything on an exchange ‘for now’ has a way of becoming forever. Set a date to decide.",
    ],
  },
  {
    slug: "first-doge-checklist",
    title: "First DOGE checklist",
    pillar: "safety",
    summary: "Your first week with Dogecoin — slow, reversible, ego-free.",
    hook: "Start tiny. Competence compounds faster than bravado.",
    tags: ["checklist", "beginner"],
    related: [
      "uk-buying-basics",
      "wallets-explained",
      "fees-and-speed",
      "phishing-red-flags",
      "what-is-dogecoin",
    
      "volatility-psychology",
      "onboarding-a-friend",
      "stable-habits",
      "weekend-safety-drill",
      "uk-payment-rails",
    ],
    body: [
      "Write your goal in one sentence: learn, tip, long curiosity, or something else. Goals prevent FOMO shopping.",
      "Fund only what you can emotionally delete. Then practice a receive, a send, and a backup restore.",
      "Turn off notification dopamine where you can. Price apps train panic.",
      "When you feel rushed, open the phishing page on this site before you click anything else.",
    ],
  },
  {
    slug: "uk-buying-basics",
    title: "Buying DOGE in the UK — basics",
    pillar: "clarity",
    summary: "High-level on-ramp ideas without platform cheerleading.",
    hook: "The buy button is easy. The aftermath is the curriculum.",
    tags: ["uk", "buy", "beginner"],
    related: [
      "first-doge-checklist",
      "exchange-vs-wallet",
      "not-financial-advice",
      "common-mistakes",
      "fees-and-speed",
    
      "liquidity-basics",
      "uk-tax-mindset",
      "market-orders-basics",
      "uk-payment-rails",
      "exchange-account-hygiene",
    
      "exchange-outages",
      "dogecoin-and-banks-uk",
    ],
    body: [
      "Use regulated, well-known venues you researched yourself. Avoid ‘too helpful’ strangers with referral urgency.",
      "Expect identity checks. That friction is often a safety feature, not a conspiracy.",
      "After purchase, decide custody deliberately. Default inertia favours the exchange.",
      "Again: not advice — a map of decisions you should make awake.",
    ],
  },
  {
    slug: "common-mistakes",
    title: "Common mistakes",
    pillar: "safety",
    summary: "The greatest hits of avoidable pain.",
    hook: "Most losses are procedural, not cosmic.",
    tags: ["mistakes", "safety"],
    related: [
      "address-hygiene",
      "seed-phrases",
      "fake-giveaways",
      "fees-and-speed",
      "first-doge-checklist",
    
      "volatility-psychology",
      "common-send-mistakes",
    ],
    body: [
      "Sending to the wrong chain or address. Always verify the first and last characters slowly.",
      "Screenshotting seed phrases into camera rolls that sync to the cloud.",
      "Trusting ‘support’ that messages first.",
      "Sizing positions based on group chat courage instead of personal sleep quality.",
    ],
  },
  {
    slug: "address-hygiene",
    title: "Address hygiene",
    pillar: "safety",
    summary: "Copy, paste, verify — the ritual that saves fortunes.",
    hook: "Your clipboard is an attack surface.",
    tags: ["addresses", "opsec"],
    related: [
      "common-mistakes",
      "phishing-red-flags",
      "fees-and-speed",
      "wallets-explained",
      "self-custody-checklist",
    
      "test-transactions",
      "dust-and-spam",
      "qr-code-hygiene",
      "address-poisoning",
    ],
    body: [
      "Malware can swap addresses on your clipboard. Verify on the device screen, not only in your head.",
      "Save known addresses with labels. Prefer QR for in-person where possible.",
      "For large moves: send dust, confirm receipt, then send the rest.",
      "If anything looks off by one character, abort. The network will not pity you.",
    ],
  },
  {
    slug: "fake-giveaways",
    title: "Fake giveaways",
    pillar: "safety",
    summary: "Double-your-DOGE theatres and reply-with-screenshot traps.",
    hook: "If you must send coins to receive coins, it’s not a gift.",
    tags: ["scams", "giveaways"],
    related: [
      "phishing-red-flags",
      "scam-patterns-uk",
      "support-impersonation",
      "culture-and-memes",
      "if-you-got-scammed",
    
      "charity-and-causes",
      "moderation-playbook",],
    body: [
      "Celebrity-face giveaways are industrial fraud. The real person is not in the replies.",
      "‘Send 10 get 20’ is not generosity — it’s a funnel.",
      "Meme culture makes these scams blend in. That is why belonging pages and safety pages must interlink.",
      "Mute, report, move on. Engagement is oxygen.",
    ],
  },
  {
    slug: "support-impersonation",
    title: "Support impersonation",
    pillar: "safety",
    summary: "Fake agents, ticket theatre, and screen-share disasters.",
    hook: "Real support rarely DMs first. Fake support always does.",
    tags: ["scams", "support"],
    related: [
      "phishing-red-flags",
      "scam-patterns-uk",
      "seed-phrases",
      "fake-giveaways",
      "if-you-got-scammed",
    
      "screenshot-scams",],
    body: [
      "Impersonators create urgency: locked account, suspicious login, refund window closing.",
      "They want remote access or seeds. Deny both. Hang up. Use official channels you typed.",
      "UK call spoofing exists. Caller ID is costume jewellery.",
      "Write down what happened. Patterns help others even when funds don’t return.",
    ],
  },
  {
    slug: "if-you-got-scammed",
    title: "If you got scammed",
    pillar: "safety",
    summary: "Damage control without shame spirals.",
    hook: "Shame is the scammer’s second product. Don’t buy it.",
    tags: ["recovery", "safety", "uk"],
    related: [
      "scam-patterns-uk",
      "phishing-red-flags",
      "seed-phrases",
      "self-custody-checklist",
      "uk-community-pulse",
    
      "device-compromise",
      "uk-scam-reporting",
    ],
    body: [
      "Move remaining funds to a new wallet if keys may be exposed. Rotate passwords and enable 2FA elsewhere.",
      "Contact your bank/exchange fraud teams quickly for fiat on-ramps. Document txids and screenshots.",
      "Ignore recovery DMs. They are predators hunting the injured.",
      "Tell one trusted human. Isolation makes the next scam easier.",
    ],
  },
  {
    slug: "why-people-buy-doge",
    title: "Why people buy DOGE",
    pillar: "belonging",
    summary: "Culture, humour, payments experiments, and yes — speculation. Named plainly.",
    hook: "Motives are mixed. Honesty beats branding.",
    tags: ["culture", "motives"],
    related: [
      "is-dogecoin-a-joke",
      "not-financial-advice",
      "culture-and-memes",
      "inflation-and-supply",
      "what-is-dogecoin",
    
      "influencer-disclosures",],
    body: [
      "Some buy for the joke. Some for the community. Some for speculation. Some for tipping experiments.",
      "None of those motives require you to pretend it’s risk-free.",
      "This site won’t moralise your motive. It will insist on safety literacy either way.",
      "Belonging means you can say ‘I don’t know yet’ without getting ejected from the pack.",
    ],
  },
  {
    slug: "uk-community-pulse",
    title: "UK community pulse",
    pillar: "belonging",
    hub: true,
    summary: "A living stub for meetups, tone, and local signal — without pretending we’re a foundation.",
    hook: "Local beats loud.",
    tags: ["uk", "community"],
    related: [
      "why-uk-domain",
      "culture-and-memes",
      "much-wow-lexicon",
      "unofficial-disclaimer",
      "join-the-list",
    
      "meetups-and-irl",
      "creators-and-builders",
      "community-moderation",
      "dogecoin-etiquette",
      "community-glossary-uk",
      "community-care",
    ],
    body: [
      "UK Dogecoin energy tends to be dryer humour, sharper scam awareness, and less carnival barking.",
      "We’ll grow this page with community notes, reading lists, and event pointers as they earn trust.",
      "If you run a meetup, lead with safety and clarity — belonging follows.",
      "Want updates? Use Join on the home page — the quiet doorbell for the UK list.",
    ],
  },
  {
    slug: "much-wow-lexicon",
    title: "Much wow lexicon",
    pillar: "belonging",
    summary: "Community phrases decoded so you can participate without cringe panic.",
    hook: "Speaking the dialect is optional. Understanding it is power.",
    tags: ["culture", "glossary"],
    related: [
      "culture-and-memes",
      "doge-glossary",
      "is-dogecoin-a-joke",
      "uk-community-pulse",
      "fake-giveaways",
    
      "meme-literacy",],
    body: [
      "Much wow / such scarce / very currency: playful broken English from early meme format. Affectionate, not illiteracy.",
      "To the moon: aspiration slang. Not a schedule.",
      "Tips and ‘do only good everyday’ point at the kinder strain of the culture — still verify before you click.",
      "When slang is used to rush a transaction, the dialect became a weapon. Switch to safety mode.",
    ],
  },
  {
    slug: "myths-to-ignore",
    title: "Myths to ignore",
    pillar: "clarity",
    summary: "Certainty cosplay, guaranteed returns, and other bedtime stories.",
    hook: "If it removes all doubt, it’s probably marketing.",
    tags: ["myths", "clarity"],
    related: [
      "inflation-and-supply",
      "is-dogecoin-a-joke",
      "not-financial-advice",
      "dogecoin-vs-bitcoin",
      "why-people-buy-doge",
    ],
    body: [
      "‘It’s too late’ and ‘it’s guaranteed’ are twin scams of emotion.",
      "‘Everyone is getting rich’ is selection bias wearing a tracksuit.",
      "‘This site is official’ — we already told you we aren’t. Others will lie.",
      "Clarity is comfortable with unfinished answers. That’s adult.",
    ],
  },
  {
    slug: "proof-matrix",
    title: "Why trust this site",
    pillar: "belonging",
    summary: "The operating rules we publish so you can judge us in public.",
    hook: "Trust is a checklist you can read before you rely on anything.",
    tags: ["trust", "about"],
    related: [
      "why-uk-domain",
      "unofficial-disclaimer",
      "not-financial-advice",
      "phishing-red-flags",
      "join-the-list",
    ],
    body: [
      "UK presence without fake authority. Unofficial on purpose. Zero price prophecy.",
      "Guides should leave you with a next useful step — Clarity, Safety, or Belonging — not a dead end.",
      "If we break these rules, call it out. The pack polices the tone.",
      "Bookmark this page when someone asks why dogecoin.co.uk feels calmer than the carnival.",
    ],
  },
  {
    slug: "join-the-list",
    title: "Join the UK list",
    pillar: "belonging",
    summary: "Occasional useful updates — not noise, not price calls.",
    hook: "Signal only. No carnival barkers.",
    tags: ["updates", "community"],
    related: [
      "uk-community-pulse",
      "why-uk-domain",
      "first-doge-checklist",
      "phishing-red-flags",
      "proof-matrix",
    
      "creators-and-builders",],
    body: [
      "Use Join on the home page to request the update stream that matches you: explainers, safety, community, or builders.",
      "We show UK desk hours so you know when a human is likely to reply.",
      "Your request opens your mail client on purpose — clearer intent, fewer dark patterns.",
      "Belonging scales through useful drops, not daily spam.",
    ],
  },
  {
    slug: "tipping-culture",
    title: "Tipping culture",
    pillar: "belonging",
    summary: "How DOGE tip culture works — and how scammers counterfeit it.",
    hook: "Generosity is the brand. Impersonation is the parasite.",
    tags: ["culture", "tips"],
    related: [
      "culture-and-memes",
      "fake-giveaways",
      "much-wow-lexicon",
      "phishing-red-flags",
      "uk-community-pulse",
    
      "charity-and-causes",
      "dogecoin-tips-irl",],
    body: [
      "Dogecoin’s tip culture taught a generation that micro-generosity can be playful.",
      "Scammers copy the warmth and add a payment demand. Real tips never require you to send first to a stranger’s ‘matching’ address.",
      "If a tip request arrives with urgency, it is not a tip.",
      "Belonging means protecting the generous impulse from becoming an attack surface.",
    ],
  },
  {
    slug: "hardware-wallets",
    title: "Hardware wallets",
    pillar: "safety",
    summary: "When a hardware device is worth it — and when it is theatre.",
    hook: "Cold storage is a tool, not a personality.",
    tags: ["hardware", "custody"],
    related: [
      "self-custody-checklist",
      "seed-phrases",
      "wallets-explained",
      "exchange-vs-wallet",
      "first-doge-checklist",
    
      "multisig-basics",
      "cold-storage-tiers",
      "hardware-wallet-first-hour",
    ],
    body: [
      "Hardware wallets keep keys offline for most signing flows. That reduces malware risk for larger balances.",
      "They do not fix bad habits: phishing sites, photographed seeds, or blind trust in ‘setup helpers.’",
      "Buy from official channels. Used devices are a horror genre.",
      "Start with software for learning amounts; graduate hardware when the sleep-at-night number demands it.",
    ],
  },
  {
    slug: "confirmations-explained",
    title: "Confirmations explained",
    pillar: "clarity",
    summary: "Why waits exist, and how many is ‘enough’ for different stakes.",
    hook: "Finality is a gradient, not a gong.",
    tags: ["network", "basics"],
    related: [
      "how-dogecoin-works",
      "fees-and-speed",
      "address-hygiene",
      "first-doge-checklist",
      "common-mistakes",
    
      "network-congestion",
      "how-confirmations-feel",
    ],
    body: [
      "Each new block buried on top of your transaction makes reversal harder.",
      "Coffee-money and house-money deserve different patience. Match confirmation depth to consequence.",
      "Exchanges set their own deposit thresholds. Those rules are risk policies, not cosmic law.",
      "If someone demands you treat an unconfirmed tx as sacred settlement, slow down.",
    ],
  },
  {
    slug: "social-engineering",
    title: "Social engineering 101",
    pillar: "safety",
    summary: "How trust is hacked without touching code.",
    hook: "The vulnerability is often kindness.",
    tags: ["scams", "psychology"],
    related: [
      "scam-patterns-uk",
      "support-impersonation",
      "phishing-red-flags",
      "if-you-got-scammed",
      "fake-giveaways",
      "avoiding-urgency-traps",
    ],
    body: [
      "Social engineering scripts borrow authority, fear, romance, or greed — then ask for a small irreversible step.",
      "UK phone and WhatsApp vectors are common. Verify through a second channel you initiate.",
      "Practice saying ‘I’ll call you back on the official number.’ It feels rude. It is adult.",
      "Safety literacy is emotional literacy under pressure.",
    ],
  },
  {
    slug: "dogecoin-history",
    title: "A short Dogecoin history",
    pillar: "clarity",
    summary: "From joke fork to cultural fixture — the arc without mythology overload.",
    hook: "Origin stories explain tone. They do not predict price.",
    tags: ["history", "culture"],
    related: [
      "what-is-dogecoin",
      "is-dogecoin-a-joke",
      "culture-and-memes",
      "dogecoin-vs-bitcoin",
      "why-uk-domain",
    ],
    body: [
      "Dogecoin launched in 2013 as a light-hearted fork culture experiment and somehow refused to die.",
      "Attention cycles came in waves. Each wave onboarded new humans and new predators.",
      "History helps you spot recycled narratives dressed as novelty.",
      "Read it for orientation, not nostalgia investment thesis cosplay.",
    ],
  },
  {
    slug: "meetups-and-irl",
    title: "Meetups and IRL",
    pillar: "belonging",
    summary: "How to gather in the UK without turning into a pitch room.",
    hook: "The best meetup ends with people safer than they arrived.",
    tags: ["uk", "community", "irl"],
    related: [
      "uk-community-pulse",
      "phishing-red-flags",
      "first-doge-checklist",
      "why-uk-domain",
      "tipping-culture",
    
      "community-moderation",
      "dogecoin-tips-irl",
      "uk-meetup-safety",],
    body: [
      "Open with a safety five minutes. Normalise seed hygiene talk like you normalise fire exits.",
      "Avoid on-stage price prophecy. Teach a skill: address verify, wallet backup, scam teardown.",
      "Publish notes afterward so remote UK folks inherit the signal.",
      "Belonging scales when IRL generosity meets online clarity.",
    ],
  },
  {
    slug: "password-and-2fa",
    title: "Passwords and 2FA",
    pillar: "safety",
    summary: "Exchange hygiene that prevents the boring disasters.",
    hook: "Most ‘hacks’ are reused passwords with better marketing.",
    tags: ["opsec", "exchange"],
    related: [
      "exchange-vs-wallet",
      "scam-patterns-uk",
      "support-impersonation",
      "self-custody-checklist",
      "common-mistakes",
    
      "stable-habits",
      "public-wifi-risks",
      "sim-swap-awareness",
      "exchange-account-hygiene",
    
      "withdrawal-allowlists",],
    body: [
      "Unique passwords. A manager. App-based or hardware 2FA over SMS when you can.",
      "SIM-swap is a UK-relevant threat. SMS 2FA is better than nothing and worse than app 2FA.",
      "Withdrawal allowlists add friction that saves careers.",
      "Boring security is elite security.",
    ],
  },
  {
    slug: "reading-block-explorers",
    title: "Reading block explorers",
    pillar: "clarity",
    summary: "How to verify a send yourself without trusting a screenshot.",
    hook: "Screenshots lie. Explorers gossip truthfully.",
    tags: ["tools", "network"],
    related: [
      "confirmations-explained",
      "how-dogecoin-works",
      "address-hygiene",
      "fees-and-speed",
      "common-mistakes",
    
      "dust-and-spam",
      "transaction-notes",
      "screenshot-scams",],
    body: [
      "Paste a txid into a reputable explorer. Confirm amount, addresses, and confirmation count.",
      "Never trust a cropped image from a stranger as proof of payment.",
      "Learn the difference between ‘broadcast’ and ‘confirmed.’",
      "Clarity tools turn anxiety into checkable facts.",
    ],
  },
  {
    slug: "creators-and-builders",
    title: "Creators and builders",
    pillar: "belonging",
    summary: "Making things in the DOGE orbit without extractive hustle energy.",
    hook: "Build for the pack, not the extract.",
    tags: ["builders", "community"],
    related: [
      "uk-community-pulse",
      "join-the-list",
      "culture-and-memes",
      "why-uk-domain",
      "proof-matrix",
    ],
    body: [
      "Tools, explainers, art, and meetup ops all count as building.",
      "Disclose affiliations. Hidden bags plus loud advice is a trust tax.",
      "Ship useful docs. Memes without manuals strand newcomers.",
      "UK builders: document in .co.uk English — dry, clear, kind.",
    ],
  },
  {
    slug: "paper-wallets",
    title: "Paper wallets",
    pillar: "safety",
    summary: "Paper backups: when they help and how they fail.",
    hook: "Analog is not automatically safe.",
    tags: ["custody", "backup"],
    related: [
      "seed-phrases",
      "self-custody-checklist",
      "hardware-wallets",
      "common-mistakes",
      "wallets-explained",
    
      "cold-storage-tiers",],
    body: [
      "A paper wallet is usually a printed or handwritten backup of keys or a seed — useful when you want something offline that does not depend on a phone battery.",
      "Paper fails in ordinary ways: water, fire, fading ink, being photographed ‘just in case,’ or left in a drawer someone else can find.",
      "If you use paper, treat it like cash in a safe: offline, durable packaging, no cloud photos, and a tested restore path.",
      "For many people a metal seed backup plus a hardware wallet is calmer than a clever DIY printout. Pick boring on purpose.",
    ],
  },
  {
    slug: "multisig-basics",
    title: "Multisig basics",
    pillar: "safety",
    summary: "Shared control without shared chaos.",
    hook: "One key is a single story.",
    tags: ["custody", "advanced"],
    related: [
      "self-custody-checklist",
      "hardware-wallets",
      "seed-phrases",
      "wallets-explained",
      "exchange-vs-wallet",
    ],
    body: [
      "Multisig means more than one key must approve a spend. It reduces the ‘one stolen phone empties everything’ failure mode.",
      "It also adds process: more devices, more backups, more ways to lock yourself out if you improvise.",
      "Start by understanding single-signature custody well. Multisig is for amounts and life situations that justify the extra ceremony.",
      "UK practical note: document who holds which key and how recovery works — secrets that only live in one head are not a plan.",
    ],
  },
  {
    slug: "liquidity-basics",
    title: "Liquidity basics",
    pillar: "clarity",
    summary: "Why the price you see is not always the price you get.",
    hook: "Screens lie politely.",
    tags: ["markets", "basics"],
    related: [
      "uk-buying-basics",
      "fees-and-speed",
      "not-financial-advice",
      "common-mistakes",
      "why-people-buy-doge",
    
      "market-orders-basics",
      "spread-and-slippage",],
    body: [
      "The price on a big chart is a headline. The price you get depends on how deep the market is when you trade and how large your order is.",
      "Thin liquidity means small buys or sells can move the price against you. That gap is not a conspiracy — it is market depth.",
      "Exchanges and pairs differ. A quiet Sunday and a viral Monday are not the same shopping trip.",
      "This is mechanics, not advice: size down when books look thin, and never treat a screenshot mid-candle as a promise.",
    ],
  },
  {
    slug: "volatility-psychology",
    title: "Volatility psychology",
    pillar: "belonging",
    summary: "How fear and euphoria hijack good procedures.",
    hook: "Your nervous system is part of the stack.",
    tags: ["psychology", "culture"],
    related: [
      "first-doge-checklist",
      "common-mistakes",
      "not-financial-advice",
      "why-people-buy-doge",
      "social-engineering",
    
      "hype-cycle-literacy",
      "watching-without-watching",
    ],
    body: [
      "Price swings hijack attention. Fear and euphoria both push people to skip the boring checks they already know.",
      "A useful rule: when your body feels urgent, your procedure gets longer — not shorter. Verify addresses twice. Pause DMs.",
      "Belonging helps here: calm friends beat hype group chats. Mute threads that treat every candle as destiny.",
      "You are allowed to sit out a carnival. Literacy includes knowing when not to click.",
    ],
  },
  {
    slug: "charity-and-causes",
    title: "Charity and causes",
    pillar: "belonging",
    summary: "DOGE charity energy — verify before you donate.",
    hook: "Kindness attracts counterfeits.",
    tags: ["culture", "trust"],
    related: [
      "tipping-culture",
      "fake-giveaways",
      "phishing-red-flags",
      "culture-and-memes",
      "uk-community-pulse",
    ],
    body: [
      "Dogecoin culture has a real kindness streak — tips, fundraisers, and cause energy that feels like the point.",
      "Scammers wear the same costume. Fake charity wallets, lookalike orgs, and ‘match my donation’ pressure are common.",
      "Verify the organisation independently, prefer known channels, and never send to an address that arrived only in a DM.",
      "Warmth without verification is how good people fund bad actors. Kindness still checks the invoice.",
    ],
  },
  {
    slug: "nodes-and-clients",
    title: "Nodes and clients",
    pillar: "clarity",
    summary: "What running software for the network actually means.",
    hook: "Participation has layers.",
    tags: ["network", "software"],
    related: [
      "how-dogecoin-works",
      "mining-and-security",
      "reading-block-explorers",
      "what-is-dogecoin",
      "confirmations-explained",
    
      "open-source-trust",],
    body: [
      "A node is software that talks to the Dogecoin network: it relays transactions, checks rules, and helps keep a shared history honest.",
      "Most people use a light wallet that trusts other infrastructure. Running a full client is optional participation, not a moral exam.",
      "If you run software, download it from sources you typed yourself and verify releases the way the project recommends.",
      "You do not need a rack of servers to belong here — understanding what a node is already removes a layer of mystery.",
    ],
  },
  {
    slug: "mobile-wallet-hygiene",
    title: "Mobile wallet hygiene",
    pillar: "safety",
    summary: "Phones are convenient attack surfaces.",
    hook: "Your pocket computer is a fortress only if you treat it like one.",
    tags: ["mobile", "opsec"],
    related: [
      "wallets-explained",
      "seed-phrases",
      "phishing-red-flags",
      "password-and-2fa",
      "self-custody-checklist",
    
      "public-wifi-risks",
      "device-compromise",],
    body: [
      "Phones are wonderful for small amounts and terrible as the only vault for life-changing balances.",
      "Keep the OS updated, lock the device, avoid random wallet apps, and never type a seed into a website ‘to restore.’",
      "Screen overlays, malicious keyboards, and fake apps exist. Install from places you navigated to on purpose.",
      "If you travel or use public Wi‑Fi, treat signing moments as higher risk — or wait until you are on trusted connectivity.",
    ],
  },
  {
    slug: "uk-tax-mindset",
    title: "UK tax mindset",
    pillar: "clarity",
    summary: "Record-keeping mindset — not advice, just future-you kindness.",
    hook: "HMRC does not accept vibes.",
    tags: ["uk", "records"],
    related: [
      "uk-buying-basics",
      "not-financial-advice",
      "exchange-vs-wallet",
      "first-doge-checklist",
      "why-uk-domain",
    
      "transaction-notes",],
    body: [
      "This is not tax advice. It is a mindset: crypto activity can create records you will wish you had later.",
      "Note dates, amounts, fees, and why you moved funds — in a private system you control, not only in exchange UIs.",
      "Exchanges change products. Screenshots rot. A simple spreadsheet habit beats forensic archaeology.",
      "When in doubt, ask a qualified UK professional about your situation. Calm records make that conversation cheaper.",
    ],
  },
  {
    slug: "influencer-disclosures",
    title: "Influencer disclosures",
    pillar: "belonging",
    summary: "How to read paid enthusiasm without becoming the exit liquidity.",
    hook: "Charisma is not due diligence.",
    tags: ["culture", "media"],
    related: [
      "why-people-buy-doge",
      "not-financial-advice",
      "social-engineering",
      "fake-giveaways",
      "proof-matrix",
    
      "hype-cycle-literacy",],
    body: [
      "Charisma sells. Disclosures often arrive in tiny fonts — if they arrive at all.",
      "Treat loud certainty about price as entertainment until proven otherwise. Ask what they gain if you click.",
      "Paid promotions, referral links, and ‘educational’ channels can still be sales funnels with better lighting.",
      "Your belonging does not require you to copy anyone’s bag. Borrow curiosity; keep your own checklist.",
    ],
  },
  {
    slug: "test-transactions",
    title: "Test transactions",
    pillar: "safety",
    summary: "The tiny send that prevents the huge regret.",
    hook: "Ritual beats bravado.",
    tags: ["checklist", "opsec"],
    related: [
      "address-hygiene",
      "fees-and-speed",
      "first-doge-checklist",
      "common-mistakes",
      "confirmations-explained",
    
      "qr-code-hygiene",],
    body: [
      "Before a meaningful send, ship a dust amount to the same address and wait for confirmation you can see.",
      "That ritual catches typos, wrong networks, malicious QR overlays, and ‘I pasted the old address’ mistakes.",
      "Scammers hate delays. Anyone who demands you skip the test is volunteering as a risk signal.",
      "Make the test send boring and automatic — like locking a door — so adrenaline cannot talk you out of it.",
    ],
  },
  {
    slug: "forks-and-clones",
    title: "Forks and clones",
    pillar: "clarity",
    summary: "Lookalike coins and why names are not destiny.",
    hook: "Branding is cheap. Networks are not.",
    tags: ["basics", "risk"],
    related: [
      "what-is-dogecoin",
      "dogecoin-vs-bitcoin",
      "phishing-red-flags",
      "myths-to-ignore",
      "doge-glossary",
    ],
    body: [
      "A familiar doge face on a listing is not the same as Dogecoin. Names and memes are cheap to copy.",
      "Check tickers, contract or network details where relevant, and whether you are somehow off the asset you meant.",
      "Clones often appear during hype waves because attention is the distribution channel.",
      "If you are unsure, stop and re-read a primary explainer — confusion is cheaper than a wrong deposit.",
    ],
  },
  {
    slug: "community-moderation",
    title: "Community moderation",
    pillar: "belonging",
    summary: "Keeping UK spaces kind without becoming a cult.",
    hook: "Boundaries are hospitality.",
    tags: ["community", "uk"],
    related: [
      "uk-community-pulse",
      "meetups-and-irl",
      "phishing-red-flags",
      "unofficial-disclaimer",
      "creators-and-builders",
    
      "uk-meetup-safety",
      "moderation-playbook",],
    body: [
      "Good UK spaces feel welcoming and bounded: humour yes, fake support DMs no, seed requests never.",
      "Moderation is hospitality. Removing spam and pressure tactics protects newcomers without turning chats into purity contests.",
      "Pin plain rules. Repeat them when markets get loud. Consistency beats clever one-off judgements.",
      "Belonging scales when people know the room will not abandon them to predators for engagement metrics.",
    ],
  },
  {
    slug: "cold-storage-tiers",
    title: "Cold storage tiers",
    pillar: "safety",
    summary: "Match custody tier to amount and life chaos.",
    hook: "Not everything needs a vault. Some things do.",
    tags: ["custody", "tiers"],
    related: [
      "hardware-wallets",
      "paper-wallets",
      "self-custody-checklist",
      "exchange-vs-wallet",
      "first-doge-checklist",
    
      "hot-wallet-limits",],
    body: [
      "Match custody to amount and chaos. Pocket change can live hot; rent money should not.",
      "Tier 1: exchange or phone wallet for learning amounts. Tier 2: self-custody with tested backups. Tier 3: hardware and offline habits for serious balances.",
      "Moving up a tier should be boring and rehearsed — not improvised during a spike.",
      "The goal is sleep, not maximal cosplay. Complexity you cannot operate is not security.",
    ],
  },
  {
    slug: "meme-literacy",
    title: "Meme literacy",
    pillar: "belonging",
    summary: "Reading jokes so you do not fund them blindly.",
    hook: "Laughter is onboarding — and camouflage.",
    tags: ["culture", "literacy"],
    related: [
      "culture-and-memes",
      "much-wow-lexicon",
      "fake-giveaways",
      "is-dogecoin-a-joke",
      "tipping-culture",
    ],
    body: [
      "Memes onboard people faster than whitepapers. They also camouflage urgency, fake giveaways, and tribal pressure.",
      "Laugh, then verify. A joke that demands a seed, a connect, or an immediate send is not a joke.",
      "Learn the lexicon so slang cannot hide a scam script. Belonging includes shared language — and shared red lines.",
      "You can love the culture and still refuse to fund a punchline aimed at your wallet.",
    ],
  },
  {
    slug: "network-congestion",
    title: "Network congestion",
    pillar: "clarity",
    summary: "What busy moments feel like and how to respond.",
    hook: "Patience is a fee strategy.",
    tags: ["fees", "network"],
    related: [
      "fees-and-speed",
      "confirmations-explained",
      "how-dogecoin-works",
      "reading-block-explorers",
      "common-mistakes",
    ],
    body: [
      "Busy moments mean more competition for block space. Fees and wait times can rise; panic usually makes them feel worse.",
      "If a send is not urgent, waiting is a valid strategy. If it is urgent, pay for priority without rage-clicking twice.",
      "Double-broadcasting because you are impatient can create confusion — read your wallet’s status calmly.",
      "Congestion is weather. Pack a procedure, not a prophecy.",
    ],
  },
  {
    slug: "family-and-inheritance",
    title: "Family and inheritance",
    pillar: "safety",
    summary: "Harsh topic, practical notes for shared reality.",
    hook: "Secrets that die with you are not a plan.",
    tags: ["custody", "life"],
    related: [
      "seed-phrases",
      "self-custody-checklist",
      "multisig-basics",
      "hardware-wallets",
      "not-financial-advice",
    ],
    body: [
      "If only you know how to recover the wallet, your family inherits a mystery box.",
      "This is not legal advice. It is a prompt: document a recovery path a trusted person can follow without improvising under grief.",
      "Share enough to recover, not enough to casually spend. Multisig or sealed instructions can help some households.",
      "Have the awkward conversation once while everyone is calm. Future-you will not get a better moment.",
    ],
  },
  {
    slug: "onboarding-a-friend",
    title: "Onboarding a friend",
    pillar: "belonging",
    summary: "Teach DOGE without dunking or dumping risk on them.",
    hook: "The best flex is someone else staying safe.",
    tags: ["community", "teaching"],
    related: [
      "first-doge-checklist",
      "phishing-red-flags",
      "what-is-dogecoin",
      "meetups-and-irl",
      "tipping-culture",
    
      "newcomer-script",],
    body: [
      "Teach the mental model and one safety rule before you teach the meme: never share a seed phrase.",
      "Offer a tiny practice send and two calm links — one clarity, one safety — instead of a portfolio pep talk.",
      "Do not dunk on beginners. Humiliation pushes people into the arms of louder, worse teachers.",
      "The flex is a friend who still has their coins and their dignity next month.",
    ],
  },
  {
    slug: "stable-habits",
    title: "Stable habits",
    pillar: "safety",
    summary: "Daily/weekly rituals that reduce unforced errors.",
    hook: "Discipline is a safety feature.",
    tags: ["habits", "checklist"],
    related: [
      "first-doge-checklist",
      "password-and-2fa",
      "address-hygiene",
      "volatility-psychology",
      "common-mistakes",
    ],
    body: [
      "Safety is mostly boring repetition: updates, locks, bookmarks, test sends, and not rushing DMs.",
      "Weekly: skim account alerts, confirm your backup still exists, delete a phishing email without clicking.",
      "During hype: shrink size, lengthen checks, mute the loudest rooms.",
      "Habits beat heroics. Design a routine you will actually keep on a tired Tuesday.",
    ],
  },
  {
    slug: "open-source-trust",
    title: "Open source trust",
    pillar: "clarity",
    summary: "How to think about software trust without becoming a auditor cosplay.",
    hook: "Verify what you can. Contain what you cannot.",
    tags: ["software", "trust"],
    related: [
      "wallets-explained",
      "nodes-and-clients",
      "phishing-red-flags",
      "self-custody-checklist",
      "proof-matrix",
    ],
    body: [
      "Open source means more eyes can look — not that you personally audited every line.",
      "Practical trust: known projects, official download paths, signed releases where offered, and small amounts while you learn.",
      "Closed apps can be fine for tiny experiments and terrible as unexplained vaults. Ask what failure looks like.",
      "Contain risk you cannot verify. That is clarity, not paranoia.",
    ],
  },
  {
    slug: "uk-search-intent",
    title: "Finding DOGE answers in the UK",
    pillar: "belonging",
    summary: "Why UK visitors look for a calm local explanation — and how this site responds.",
    hook: "The search is usually a feeling wearing keywords.",
    tags: ["uk", "beginner", "trust"],
    related: [
      "why-uk-domain",
      "what-is-dogecoin",
      "phishing-red-flags",
      "join-the-list",
      "proof-matrix",
    ],
    body: [
      "People search for Dogecoin in the UK because they want a calm local explanation — not a carnival tip.",
      "Typical quiet questions: what is it, is it a scam, how do wallets work, and where do I start without looking foolish.",
      "This site answers those questions in plain English, marks itself unofficial, and refuses price prophecy on purpose.",
      "If that is why you arrived: you are in the right place. Pick Clarity, Safety, or Belonging and take the next link.",
    ],
  },
  {
    slug: "dust-and-spam",
    title: "Dust and spam",
    pillar: "clarity",
    summary: "Tiny unexpected amounts and why they appear.",
    hook: "Not every surprise is a gift.",
    tags: ["network", "privacy"],
    related: [
      "address-hygiene",
      "reading-block-explorers",
      "phishing-red-flags",
      "wallets-explained",
      "common-mistakes",
    
      "address-poisoning",],
    body: [
      "Dust is a tiny unexpected amount landing in a wallet. Sometimes it is noise; sometimes it is a tracking or social trick.",
      "Do not rush to ‘claim,’ connect, or follow instructions that arrive with the surprise.",
      "Address hygiene and not publishing a hot wallet everywhere reduces how often strangers can poke you.",
      "If something looks like a gift with homework attached, assume the homework is the attack.",
    ],
  },
  {
    slug: "hot-wallet-limits",
    title: "Hot wallet limits",
    pillar: "safety",
    summary: "How much to keep online vs cold — a practical ceiling.",
    hook: "Convenience has a balance cap.",
    tags: ["custody", "limits"],
    related: [
      "cold-storage-tiers",
      "wallets-explained",
      "self-custody-checklist",
      "first-doge-checklist",
      "stable-habits",
    ],
    body: [
      "Hot wallets are for spending and learning amounts. Cold storage is for sleep-at-night amounts.",
      "Pick a personal ceiling you can lose without wrecking your month — then enforce it.",
      "When the hot balance creeps up ‘temporarily,’ schedule the move before the next hype wave.",
      "Safety is a limit you honour when markets are loud.",
    ],
  },
  {
    slug: "qr-code-hygiene",
    title: "QR code hygiene",
    pillar: "safety",
    summary: "Scanning safely without feeding malware or wrong addresses.",
    hook: "A QR is just text wearing sunglasses.",
    tags: ["opsec", "addresses"],
    related: [
      "address-hygiene",
      "test-transactions",
      "phishing-red-flags",
      "mobile-wallet-hygiene",
      "common-mistakes",
    ],
    body: [
      "Read the decoded address before you confirm. Stickers and overlays exist in the wild.",
      "Prefer showing your receive QR from your own wallet — not a PDF someone emailed.",
      "For large moves, still do a dust test after scanning.",
      "QR convenience dies the moment you stop verifying.",
    ],
  },
  {
    slug: "public-wifi-risks",
    title: "Public Wi‑Fi risks",
    pillar: "safety",
    summary: "Cafés, airports, and the quiet ways sessions get stolen.",
    hook: "Free Wi‑Fi is rarely free of intent.",
    tags: ["opsec", "mobile"],
    related: [
      "mobile-wallet-hygiene",
      "password-and-2fa",
      "phishing-red-flags",
      "stable-habits",
      "support-impersonation",
    ],
    body: [
      "Avoid wallet ops on open networks when you can. Use trusted mobile data for signing moments.",
      "Captive portals are phishing theatres. Type known URLs yourself.",
      "VPN helps some threats and none of social engineering.",
      "If you must act on public Wi‑Fi, keep amounts tiny and eyes open.",
    ],
  },
  {
    slug: "browser-extension-risk",
    title: "Browser extension risk",
    pillar: "safety",
    summary: "Wallet extensions: power tools with sharp edges.",
    hook: "If it can sign, it can also steal.",
    tags: ["wallets", "browser"],
    related: [
      "wallets-explained",
      "phishing-red-flags",
      "open-source-trust",
      "seed-phrases",
      "hot-wallet-limits",
    ],
    body: [
      "Install only from sources you typed. Fake extensions clone icons for a living.",
      "Lock the extension when idle. Review connected sites periodically.",
      "A malicious page plus a confused click is enough — slow down on connect prompts.",
      "Serious balances do not live in the browser long-term.",
    ],
  },
  {
    slug: "backup-drill",
    title: "Backup drill",
    pillar: "safety",
    summary: "Practice restoring a wallet before you need to.",
    hook: "Untested backups are fan fiction.",
    tags: ["custody", "checklist"],
    related: [
      "seed-phrases",
      "self-custody-checklist",
      "hardware-wallets",
      "first-doge-checklist",
      "stable-habits",
    
      "recovery-phrase-storage",],
    body: [
      "Fund a tiny wallet, back it up, wipe the device path, restore, and confirm the dust is there.",
      "Do this before the balance is emotionally expensive.",
      "Note how long it took and where you got stuck — fix the process, not just the mood.",
      "A drill turns panic into muscle memory.",
    ],
  },
  {
    slug: "transaction-notes",
    title: "Transaction notes",
    pillar: "clarity",
    summary: "Labelling sends so future-you knows what happened.",
    hook: "Memory is not a ledger.",
    tags: ["habits", "records"],
    related: [
      "uk-tax-mindset",
      "reading-block-explorers",
      "first-doge-checklist",
      "stable-habits",
      "address-hygiene",
    ],
    body: [
      "Keep a private note of date, amount, counterparty label, and why — not on the public chain.",
      "UK angle: good notes reduce future stress. This is not tax advice.",
      "Screenshots alone rot. Structured notes survive.",
      "Clarity compounds when your history is readable.",
    ],
  },
  {
    slug: "utxo-mental-model",
    title: "UTXO mental model",
    pillar: "clarity",
    summary: "Coins as notes, not a single bank balance number.",
    hook: "Understanding inputs prevents weird fee surprises.",
    tags: ["network", "basics"],
    related: [
      "how-dogecoin-works",
      "fees-and-speed",
      "reading-block-explorers",
      "dust-and-spam",
      "confirmations-explained",
    ],
    body: [
      "Many cryptocurrencies track unspent outputs. Your ‘balance’ is the sum of notes you can spend.",
      "Sending may consume multiple notes and create change — explorers make this visible.",
      "Dust and spam interact with this model; that’s why address hygiene matters.",
      "You do not need to be an engineer — just stop expecting a bank UI under the hood.",
    ],
  },
  {
    slug: "market-orders-basics",
    title: "Market orders basics",
    pillar: "clarity",
    summary: "Buy/sell buttons without pretending it’s advice.",
    hook: "Execution mechanics ≠ destiny.",
    tags: ["markets", "uk"],
    related: [
      "uk-buying-basics",
      "liquidity-basics",
      "not-financial-advice",
      "fees-and-speed",
      "volatility-psychology",
    
      "spread-and-slippage",],
    body: [
      "A market order prioritises fill speed over exact price. Spreads and depth matter.",
      "During chaos, the fill can surprise you. Size down or wait.",
      "This page explains mechanics, not whether you should trade.",
      "If urgency is emotional, step away before you click.",
    ],
  },
  {
    slug: "spread-and-slippage",
    title: "Spread and slippage",
    pillar: "clarity",
    summary: "The quiet cost between the price you saw and the fill you got.",
    hook: "Screenshots are optimistic.",
    tags: ["markets", "fees"],
    related: [
      "liquidity-basics",
      "market-orders-basics",
      "uk-buying-basics",
      "fees-and-speed",
      "common-mistakes",
    ],
    body: [
      "Spread is the gap between buy and sell quotes. Slippage is movement while your order executes.",
      "Thin books and big size make both worse.",
      "Not advice — just the maths of impatience.",
      "Compare total cost, not the headline ticker alone.",
    ],
  },
  {
    slug: "dogecoin-tips-irl",
    title: "DOGE tips IRL",
    pillar: "belonging",
    summary: "Tipping in person without turning it into a scam demo.",
    hook: "Warmth needs a verify step.",
    tags: ["culture", "irl"],
    related: [
      "tipping-culture",
      "qr-code-hygiene",
      "meetups-and-irl",
      "test-transactions",
      "address-hygiene",
    ],
    body: [
      "Show a receive address from your own wallet. Confirm on both screens.",
      "Start tiny. Celebrate the ritual more than the amount.",
      "Never ‘match’ a tip to a stranger’s urgent address.",
      "IRL kindness plus verify steps is the UK brand of belonging.",
    ],
  },
  {
    slug: "uk-meetup-safety",
    title: "UK meetup safety",
    pillar: "belonging",
    summary: "Run or attend a meetup without becoming a honeypot.",
    hook: "Hospitality includes exits and boundaries.",
    tags: ["uk", "irl"],
    related: [
      "meetups-and-irl",
      "community-moderation",
      "phishing-red-flags",
      "onboarding-a-friend",
      "uk-community-pulse",
    ],
    body: [
      "Public venue, clear end time, no seed phrases on stage, no pressure to install apps on the spot.",
      "Announce that support never DMs first — say it out loud every time.",
      "Pair newcomers with a buddy for their first questions.",
      "A safe meetup grows the community offline.",
    ],
  },
  {
    slug: "moderation-playbook",
    title: "Moderation playbook",
    pillar: "belonging",
    summary: "Kick spam, keep kindness, refuse fake support theatre.",
    hook: "Tone is infrastructure.",
    tags: ["community", "trust"],
    related: [
      "community-moderation",
      "support-impersonation",
      "fake-giveaways",
      "uk-community-pulse",
      "proof-matrix",
    ],
    body: [
      "Pin rules: no price calls as gospel, no seed requests, no ‘support’ in DMs.",
      "Remove giveaway bots quickly — engagement is their oxygen.",
      "Document patterns so new mods inherit judgement, not vibes alone.",
      "Belonging scales when moderation is calm and consistent.",
    ],
  },
  {
    slug: "newcomer-script",
    title: "Newcomer script",
    pillar: "belonging",
    summary: "What to say in the first five minutes to a curious friend.",
    hook: "Teaching is belonging with a checklist.",
    tags: ["teaching", "community"],
    related: [
      "onboarding-a-friend",
      "what-is-dogecoin",
      "first-doge-checklist",
      "phishing-red-flags",
      "meme-literacy",
    ],
    body: [
      "Start with what DOGE is, what it isn’t, and one safety rule: never share a seed.",
      "Offer a tiny practice send, not a portfolio plan.",
      "Send them two links from this site — one clarity, one safety.",
      "Your tone teaches more than your tips.",
    ],
  },
  {
    slug: "hype-cycle-literacy",
    title: "Hype cycle literacy",
    pillar: "belonging",
    summary: "Recognising attention waves without riding them blind.",
    hook: "Volume is not validation.",
    tags: ["psychology", "culture"],
    related: [
      "volatility-psychology",
      "influencer-disclosures",
      "why-people-buy-doge",
      "myths-to-ignore",
      "not-financial-advice",
    ],
    body: [
      "Attention arrives in waves. Each wave onboard predators as well as people.",
      "When every chat is certain, raise your verify standards — not your size.",
      "This is literacy, not a timing strategy.",
      "Belonging includes permission to sit out the carnival.",
    ],
  },
  {
    slug: "screenshot-scams",
    title: "Screenshot scams",
    pillar: "safety",
    summary: "Fake balances, fake tickets, fake ‘proof of send’.",
    hook: "Pixels are costumes.",
    tags: ["scams", "opsec"],
    related: [
      "reading-block-explorers",
      "fake-giveaways",
      "support-impersonation",
      "phishing-red-flags",
      "social-engineering",
    ],
    body: [
      "Never accept a cropped image as settlement. Check a txid on an explorer you typed.",
      "Fake support tickets use official-looking templates. Hang up and reopen from a bookmark.",
      "If someone rushes you to ‘confirm you received it’ via screenshot, assume theatre.",
      "Explorers gossip; screenshots perform.",
    ],
  },
  {
    slug: "recovery-phrase-storage",
    title: "Recovery phrase storage",
    pillar: "safety",
    summary: "Where to put seeds that isn’t ‘in photos’ or ‘in Slack’.",
    hook: "Boring storage beats clever storage.",
    tags: ["custody", "seed"],
    related: [
      "seed-phrases",
      "paper-wallets",
      "backup-drill",
      "family-and-inheritance",
      "self-custody-checklist",
    ],
    body: [
      "Offline, durable, findable by the right person, invisible to the wrong one.",
      "Cloud photos and chat apps are common failure modes.",
      "Metal backups help against fire and coffee — still protect against theft.",
      "Test retrieval in a drill before you trust the stash.",
    ],
  },
  {
    slug: "device-compromise",
    title: "If your device is compromised",
    pillar: "safety",
    summary: "Assume malware, move funds, rotate everything.",
    hook: "Speed matters; panic does not.",
    tags: ["opsec", "incident"],
    related: [
      "if-you-got-scammed",
      "seed-phrases",
      "password-and-2fa",
      "hot-wallet-limits",
      "mobile-wallet-hygiene",
    ],
    body: [
      "From a clean device, move funds to a fresh wallet. Retire the old seed.",
      "Rotate exchange passwords and 2FA. Check allowlists and devices sessions.",
      "Do not ‘scan’ with random fix tools from DMs.",
      "Write the timeline down — patterns help later even when funds don’t return.",
    ],
  },
  {
    slug: "address-poisoning",
    title: "Address poisoning",
    pillar: "safety",
    summary: "Lookalike addresses in your history designed to trick a hasty paste.",
    hook: "Your transaction list can lie by omission — and by resemblance.",
    tags: ["scams","addresses","opsec"],
    related: [
          "address-hygiene",
          "test-transactions",
          "phishing-red-flags",
          "screenshot-scams",
          "common-mistakes"
    ],
    body: [
      "Attackers sometimes send tiny amounts from addresses that look like ones you use, hoping you copy the wrong one later.",
      "Always copy from your intended contact or wallet book — not from a random incoming line that ‘looks familiar.’",
      "Compare more than the first and last characters. Haste is the exploit.",
      "A dust test to a verified address beats a confident paste every time.",
    ],
  },
  {
    slug: "sim-swap-awareness",
    title: "SIM-swap awareness",
    pillar: "safety",
    summary: "When your phone number stops being a safe second factor.",
    hook: "If they can port your number, SMS codes become their codes.",
    tags: ["opsec","uk","2fa"],
    related: [
          "password-and-2fa",
          "support-impersonation",
          "mobile-wallet-hygiene",
          "exchange-vs-wallet",
          "stable-habits"
    ],
    body: [
      "SIM-swap attacks trick a mobile provider into moving your number so SMS codes and calls route to the attacker.",
      "Prefer app-based or hardware second factors over SMS where a service allows it.",
      "UK angle: set provider PINs/passwords and treat unexpected loss of signal as a possible security event.",
      "Exchanges and email are high-value targets — lock them down before you need the lesson.",
    ],
  },
  {
    slug: "exchange-account-hygiene",
    title: "Exchange account hygiene",
    pillar: "safety",
    summary: "Treat exchange logins like a bank tab you share with the internet.",
    hook: "Convenience accounts deserve boring paranoia.",
    tags: ["exchanges","opsec","uk"],
    related: [
          "exchange-vs-wallet",
          "password-and-2fa",
          "phishing-red-flags",
          "sim-swap-awareness",
          "uk-buying-basics"
    ],
    body: [
      "Use unique passwords, strong 2FA, and withdrawal allowlists if offered.",
      "Bookmark the real domain. Never log in from a DM link after a ‘security alert.’",
      "Keep only what you are actively using on an exchange; long-term idle balances raise the blast radius.",
      "Not advice to buy or sell — advice to not gift access to strangers.",
    ],
  },
  {
    slug: "reading-charts-calmly",
    title: "Reading charts calmly",
    pillar: "clarity",
    summary: "What candles show, what they don’t, and how to avoid fortune-teller brain.",
    hook: "A chart is a history sketch — not a prophecy engine.",
    tags: ["markets","literacy"],
    related: [
          "liquidity-basics",
          "volatility-psychology",
          "not-financial-advice",
          "hype-cycle-literacy",
          "why-people-buy-doge"
    ],
    body: [
      "Charts summarise past trades. They do not owe you a future.",
      "Zoom level changes the story. A dramatic five-minute move can be a shrug on the weekly view.",
      "Indicators are opinions with maths. Treat them as questions, not orders.",
      "If a chart makes you feel certain, step away before you act — certainty is often the tell.",
    ],
  },
  {
    slug: "dogecoin-etiquette",
    title: "Dogecoin etiquette",
    pillar: "belonging",
    summary: "How to show up in DOGE spaces without being that person.",
    hook: "Kindness is the culture — urgency is usually the counterfeit.",
    tags: ["culture","community"],
    related: [
          "culture-and-memes",
          "tipping-culture",
          "community-moderation",
          "onboarding-a-friend",
          "meme-literacy"
    ],
    body: [
      "Lead with curiosity, not flexes. Ask before you pitch. Never request seeds or ‘wallet verification.’",
      "Tips are optional joy — not an entrance fee. Pressure tips are a smell.",
      "Correct gently. Dunking on newcomers teaches them to hide questions until a scammer answers first.",
      "UK rooms especially reward dry humour and clear boundaries. Bring both.",
    ],
  },
  {
    slug: "weekend-safety-drill",
    title: "Weekend safety drill",
    pillar: "safety",
    summary: "A 20-minute Saturday checklist that prevents Monday regret.",
    hook: "Practice when nothing is on fire.",
    tags: ["habits","checklist"],
    related: [
          "stable-habits",
          "backup-drill",
          "test-transactions",
          "password-and-2fa",
          "first-doge-checklist"
    ],
    body: [
      "Confirm backups still exist. Update phone and wallet apps. Review exchange 2FA.",
      "Delete one risky browser extension or leftover ‘research’ bookmark that looks sketchy.",
      "Send yourself a dust test on a wallet you actually use — keep the muscle memory warm.",
      "End by muting one hype source. Calm is a security control.",
    ],
  },
  {
    slug: "what-dogecoin-is-not",
    title: "What Dogecoin is not",
    pillar: "clarity",
    summary: "Clear negatives so the mental model stops leaking.",
    hook: "Defining the edges makes the centre easier.",
    tags: ["basics","myths"],
    related: [
          "what-is-dogecoin",
          "myths-to-ignore",
          "is-dogecoin-a-joke",
          "not-financial-advice",
          "unofficial-disclaimer"
    ],
    body: [
      "Dogecoin is not a guaranteed return, not a bank with UK deposit protection, and not ‘official support’ in your DMs.",
      "It is not financial advice when someone on a stage shouts a number.",
      "This site is not the Foundation and not your broker.",
      "Once the negatives are clear, the useful positives — digital cash, culture, open network — sit still long enough to learn.",
    ],
  },
  {
    slug: "uk-payment-rails",
    title: "UK payment rails to crypto",
    pillar: "clarity",
    summary: "How pounds usually meet DOGE — without turning it into a shopping list of tips.",
    hook: "The on-ramp is where many first mistakes happen.",
    tags: ["uk","buying","basics"],
    related: [
          "uk-buying-basics",
          "exchange-vs-wallet",
          "not-financial-advice",
          "exchange-account-hygiene",
          "first-doge-checklist"
    ],
    body: [
      "Most UK newcomers meet crypto through an exchange account funded by familiar payment methods — with fees, delays, and verification steps.",
      "Read the fee schedule before you cheer the ticker. Spreads hide in ‘zero fee’ marketing sometimes.",
      "This is not a recommendation of any platform — only a reminder that the rail you use is part of the risk story.",
      "When in doubt, start tiny, enable 2FA first, and keep a written note of what you did.",
    ],
  },
  {
    slug: "community-glossary-uk",
    title: "UK community glossary",
    pillar: "belonging",
    summary: "Local flavour words and phrases you will hear in British DOGE chats.",
    hook: "Shared slang is a door — unless someone weaponises it.",
    tags: ["uk","culture","glossary"],
    related: [
          "much-wow-lexicon",
          "uk-community-pulse",
          "meme-literacy",
          "dogecoin-etiquette",
          "doge-glossary"
    ],
    body: [
      "You will hear global meme words and British understatement in the same thread — both are normal.",
      "‘Having a look’ can mean serious research or polite curiosity. Ask which.",
      "If slang is used to rush you past a safety step, translate it back to plain English and slow down.",
      "Belonging is easier when you can laugh at the lexicon without letting it override your checklist.",
    ],
  },
  {
    slug: "confirm-before-connect",
    title: "Confirm before you connect",
    pillar: "safety",
    summary: "Wallet-connect prompts: when to pause and what to read.",
    hook: "A connect button is a power tool, not a welcome mat.",
    tags: ["wallets","phishing","browser"],
    related: [
          "browser-extension-risk",
          "phishing-red-flags",
          "open-source-trust",
          "hot-wallet-limits",
          "fake-giveaways"
    ],
    body: [
      "Connecting a wallet tells a site who you are on-chain and often asks permission to propose transactions.",
      "Read the origin. Prefer typed bookmarks. Reject surprise prompts after a link from a stranger.",
      "You can disconnect. You can use a burner wallet for experiments. You can refuse.",
      "If the site needs your seed to ‘connect,’ it is not connecting — it is draining.",
    ],
  },
  {
    slug: "exchange-outages",
    title: "Exchange outages",
    pillar: "clarity",
    summary: "What ‘withdrawals paused’ really means for your plan.",
    hook: "Convenience risk shows up on busy days.",
    tags: ["exchange", "risk"],
    related: [
      "exchange-vs-wallet",
      "uk-buying-basics",
      "self-custody-checklist",
      "first-doge-checklist",
      "stable-habits",
    ],
    body: [
      "Venues pause under load, maintenance, or risk controls. Your coins may be unreachable on their schedule.",
      "That is a reason many people withdraw learning amounts to self-custody — not a conspiracy theory.",
      "Plan ahead of volatility if access matters to you.",
      "Clarity: platform risk is real even when the chain is fine.",
    ],
  },
  {
    slug: "withdrawal-allowlists",
    title: "Withdrawal allowlists",
    pillar: "safety",
    summary: "Friction that stops a hijacked account emptying overnight.",
    hook: "Slow is a feature.",
    tags: ["exchange", "opsec"],
    related: [
      "password-and-2fa",
      "exchange-vs-wallet",
      "exchange-outages",
      "stable-habits",
      "common-mistakes",
    ],
    body: [
      "Allowlist known addresses so new destinations need extra confirmation time.",
      "Pair with strong 2FA and unique passwords.",
      "Update the list carefully — phishing loves ‘urgent allowlist changes.’",
      "Boring account hygiene beats clever recovery stories.",
    ],
  },
  {
    slug: "seed-phrase-never-share",
    title: "Never share a seed phrase",
    pillar: "safety",
    summary: "The one rule that prevents most total losses.",
    hook: "If they need your seed, they are not helping you.",
    tags: ["seed", "scams", "basics"],
    related: [
      "seed-phrases",
      "phishing-red-flags",
      "support-impersonation",
      "fake-giveaways",
      "first-doge-checklist",
    ],
    body: [
      "A seed phrase is the master key. Anyone who has it can empty the wallet — forever.",
      "Support staff, airdrops, ‘sync’ pages, and helpful strangers in DMs never need it.",
      "If a screen asks you to type twelve or twenty-four words to continue, close it.",
      "Teach this rule before you teach tips, tickers, or jokes. It is the belonging safety belt.",
    ],
  },
  {
    slug: "dogecoin-for-parents",
    title: "Dogecoin for parents",
    pillar: "belonging",
    summary: "A calm brief when your kid asks about DOGE.",
    hook: "Curiosity is good. Unverified apps are not.",
    tags: ["uk", "family", "beginner"],
    related: [
      "what-is-dogecoin",
      "phishing-red-flags",
      "seed-phrase-never-share",
      "not-financial-advice",
      "onboarding-a-friend",
      "kids-and-crypto-talk",
    ],
    body: [
      "Dogecoin is digital money with a meme face. It can be fun to learn and risky to treat as guaranteed income.",
      "If a young person wants to explore, start with explainers and tiny amounts — not borrowed money or viral ‘giveaways.’",
      "Agree household rules: no seed sharing, no DM support, no skipping test sends.",
      "This is education culture, not a recommendation to buy. Calm beats cool.",
    ],
  },
  {
    slug: "avoiding-urgency-traps",
    title: "Avoiding urgency traps",
    pillar: "safety",
    summary: "Deadlines, countdowns, and ‘last chance’ scripts that empty wallets.",
    hook: "Legitimate help can wait five minutes.",
    tags: ["scams", "psychology", "opsec"],
    related: [
      "phishing-red-flags",
      "social-engineering",
      "volatility-psychology",
      "fake-giveaways",
      "support-impersonation",
    ],
    body: [
      "Urgency is the scam’s favourite font. Countdown timers and ‘account locked’ threats shrink your thinking.",
      "Create a personal rule: any money move that arrives with a deadline gets a pause and a second channel check.",
      "Call the institution on a number you looked up yourself — never the number in the scary message.",
      "Markets can move without you. Predators cannot eat what you refuse to rush.",
    ],
  },
  {
    slug: "how-confirmations-feel",
    title: "How confirmations feel",
    pillar: "clarity",
    summary: "Waiting for a send to settle without refreshing yourself into a mistake.",
    hook: "Pending is a status, not a personal insult.",
    tags: ["network", "basics"],
    related: [
      "confirmations-explained",
      "fees-and-speed",
      "network-congestion",
      "test-transactions",
      "reading-block-explorers",
    ],
    body: [
      "After you broadcast, the network needs time to include and bury your transaction under later blocks.",
      "Refreshing every second rarely speeds physics. It does increase the chance you double-send or click a phishing ‘speed up’ link.",
      "For everyday amounts, minutes are normal. For large amounts, patience is part of the fee you pay for calm.",
      "Use an explorer you typed yourself if you need a second opinion — not a link from a stranger.",
    ],
  },
  {
    slug: "uk-scam-reporting",
    title: "UK scam reporting basics",
    pillar: "safety",
    summary: "Where to point people after a loss — without fake recovery theatre.",
    hook: "Reporting is for patterns. Recovery DMs are often round two.",
    tags: ["uk", "scams", "incident"],
    related: [
      "if-you-got-scammed",
      "scam-patterns-uk",
      "support-impersonation",
      "screenshot-scams",
    ],
    body: [
      "If you were scammed, preserve evidence: addresses, txids, messages, and timelines. Do not pay a ‘recovery specialist’ who cold-contacts you.",
      "Use official UK reporting routes you navigate to yourself — Action Fraud and your bank/exchange support bookmarks.",
      "This page is orientation, not legal advice. A calm report helps investigators more than a panicked second payment.",
      "Tell friends the pattern. Belonging includes warning the pack.",
    ],
  },
  {
    slug: "meme-coins-vs-dogecoin",
    title: "Meme coins vs Dogecoin",
    pillar: "clarity",
    summary: "Same costume energy, different networks and risk profiles.",
    hook: "A doge face is not a network identity.",
    tags: ["basics", "risk", "compare"],
    related: [
      "what-is-dogecoin",
      "forks-and-clones",
      "what-dogecoin-is-not",
      "phishing-red-flags",
      "dogecoin-vs-bitcoin",
    ],
    body: [
      "‘Meme coin’ describes attention style. Dogecoin is a specific long-running cryptocurrency with its own history and network.",
      "Newer lookalikes can be harder to research, easier to abandon, and denser with fake listings.",
      "If someone says ‘it’s the same as DOGE,’ ask which chain, which ticker, and which download — then verify slowly.",
      "Clarity means naming the asset you mean, not the vibe you like.",
    ],
  },
  {
    slug: "community-care",
    title: "Community care",
    pillar: "belonging",
    summary: "Looking after people in DOGE spaces when markets get loud.",
    hook: "The pack is the product.",
    tags: ["community", "culture", "uk"],
    related: [
      "uk-community-pulse",
      "community-moderation",
      "volatility-psychology",
      "onboarding-a-friend",
      "dogecoin-etiquette",
    ],
    body: [
      "When price noise rises, so does loneliness, FOMO, and scam density. Care looks like slower answers and clearer boundaries.",
      "Check on quiet members. Repeat the seed rule. Pin the same safety links without shaming.",
      "Do not turn someone’s loss into content. Privacy is kindness.",
      "UK tone helps: understatement, practicality, and humour that does not punch down.",
    ],
  },
  {
    slug: "hardware-wallet-first-hour",
    title: "Hardware wallet first hour",
    pillar: "safety",
    summary: "Unbox, verify, initialise — without letting a YouTube tab drive.",
    hook: "The first hour teaches the habits that matter later.",
    tags: ["hardware", "custody", "checklist"],
    related: [
      "hardware-wallets",
      "seed-phrases",
      "backup-drill",
      "self-custody-checklist",
      "open-source-trust",
    ],
    body: [
      "Buy from a source you trust. Inspect packaging. Initialise on a device you control — never a ‘pre-set’ unit from a stranger.",
      "Write the seed offline. Do not photograph it. Confirm the device’s authenticity steps from official docs you typed.",
      "Practice a tiny receive and send before migrating serious balances.",
      "If a video asks you to enter the seed on a computer to ‘check,’ stop. That is the opposite of the product.",
    ],
  },
  {
    slug: "dogecoin-and-banks-uk",
    title: "Dogecoin and UK banks",
    pillar: "clarity",
    summary: "How bank transfers and crypto accounts usually meet — calmly.",
    hook: "Your bank app and your wallet are different planets.",
    tags: ["uk", "banks", "basics"],
    related: [
      "uk-payment-rails",
      "uk-buying-basics",
      "exchange-account-hygiene",
      "not-financial-advice",
      "scam-patterns-uk",
    ],
    body: [
      "Banks move pounds. Crypto accounts and wallets move digital assets. The bridge is usually an exchange or similar service with its own rules.",
      "Unexpected bank messages about crypto can be phishing. Use numbers and apps you already trust — not the link in the text.",
      "Fees, freezes, and verification delays are normal friction, not always a conspiracy. Read the service’s own status notes.",
      "This is orientation, not banking advice. When money feels confusing, shrink the size and slow the clicks.",
    ],
  },
  {
    slug: "kids-and-crypto-talk",
    title: "Talking crypto with kids",
    pillar: "belonging",
    summary: "Age-appropriate honesty without fear theatre or hype.",
    hook: "Curiosity deserves a seatbelt.",
    tags: ["family", "uk", "teaching"],
    related: [
      "dogecoin-for-parents",
      "seed-phrase-never-share",
      "meme-literacy",
      "what-is-dogecoin",
      "phishing-red-flags",
    ],
    body: [
      "Explain that digital money is real enough to lose and meme-y enough to trick people.",
      "Teach the seed rule early. Treat giveaways as fiction until proven otherwise.",
      "Keep amounts educational if you experiment at all — never money meant for lunch or rent.",
      "Belonging includes protecting younger people from the carnival’s sharp edges.",
    ],
  },
  {
    slug: "bookmark-hygiene",
    title: "Bookmark hygiene",
    pillar: "safety",
    summary: "Type once, bookmark forever — starve phishing links of clicks.",
    hook: "Your bookmark bar is a security control.",
    tags: ["opsec", "habits"],
    related: [
      "phishing-red-flags",
      "stable-habits",
      "exchange-account-hygiene",
      "browser-extension-risk",
      "avoiding-urgency-traps",
    ],
    body: [
      "Save the real exchange, wallet docs, and explorer URLs yourself. Use those bookmarks when something urgent appears.",
      "Delete lookalike bookmarks you added in a rush. Check the domain characters slowly.",
      "On shared computers, prefer logged-out habits and no saved seeds — ever.",
      "A boring bookmark beats a clever memory when adrenaline is high.",
    ],
  },
  {
    slug: "watching-without-watching",
    title: "Following DOGE without obsession",
    pillar: "belonging",
    summary: "Stay informed without letting charts rent your nervous system.",
    hook: "Attention is a balance you can overspend.",
    tags: ["psychology", "habits", "culture"],
    related: [
      "volatility-psychology",
      "hype-cycle-literacy",
      "stable-habits",
      "community-care",
      "reading-charts-calmly",
    ],
    body: [
      "Mute price bots if they make you worse at life. Check on a schedule, not a twitch.",
      "Prefer explainers and safety notes over minute-by-minute theatre.",
      "Belonging can be asynchronous — weekly community pulse beats hourly panic.",
      "If you only feel ‘in the pack’ while staring at candles, renegotiate the pack.",
    ],
  },
  {
    slug: "common-send-mistakes",
    title: "Common send mistakes",
    pillar: "safety",
    summary: "The errors that hurt even careful people.",
    hook: "Most losses are ordinary, not cinematic.",
    tags: ["checklist", "mistakes"],
    related: [
      "common-mistakes",
      "address-hygiene",
      "test-transactions",
      "address-poisoning",
      "fees-and-speed",
    ],
    body: [
      "Wrong address paste, skipped test send, rushed QR scan, and ‘I’ll move the rest later’ balances left hot.",
      "Sending under social pressure — livestreams, DMs, countdown pages — multiplies every mistake.",
      "Build a pre-flight: amount, asset, address compare, test dust, then the real send.",
      "Ordinary discipline beats rare genius.",
    ],
  },
];
