/**
 * Heartbeat expansion seeds — each pass consumes the next unused batch,
 * densifies links, then deploys. Agent appends consumed batches into catalog.ts.
 */
module.exports = {
  batches: [
    {
      id: "pass-01",
      pages: [
        {
          slug: "tipping-culture",
          title: "Tipping culture",
          pillar: "belonging",
          summary: "How DOGE tip culture works — and how scammers counterfeit it.",
          hook: "Generosity is the brand. Impersonation is the parasite.",
          tags: ["culture", "tips"],
          related: ["culture-and-memes", "fake-giveaways", "much-wow-lexicon", "phishing-red-flags", "uk-community-pulse"],
          body: [
            "Dogecoin’s tip culture taught a generation that micro-generosity can be playful.",
            "Scammers copy the warmth and add a payment demand. Real tips never require you to send first to a stranger’s ‘matching’ address.",
            "If a tip request arrives with urgency, it is not a tip.",
            "Belonging means protecting the generous impulse from becoming an attack surface.",
          ],
        },
        {
          slug: "hardware-wallets",
          title: "Hardware wallets",
          pillar: "safety",
          summary: "When a hardware device is worth it — and when it is theatre.",
          hook: "Cold storage is a tool, not a personality.",
          tags: ["hardware", "custody"],
          related: ["self-custody-checklist", "seed-phrases", "wallets-explained", "exchange-vs-wallet", "first-doge-checklist"],
          body: [
            "Hardware wallets keep keys offline for most signing flows. That reduces malware risk for larger balances.",
            "They do not fix bad habits: phishing sites, photographed seeds, or blind trust in ‘setup helpers.’",
            "Buy from official channels. Used devices are a horror genre.",
            "Start with software for learning amounts; graduate hardware when the sleep-at-night number demands it.",
          ],
        },
        {
          slug: "confirmations-explained",
          title: "Confirmations explained",
          pillar: "clarity",
          summary: "Why waits exist, and how many is ‘enough’ for different stakes.",
          hook: "Finality is a gradient, not a gong.",
          tags: ["network", "basics"],
          related: ["how-dogecoin-works", "fees-and-speed", "address-hygiene", "first-doge-checklist", "common-mistakes"],
          body: [
            "Each new block buried on top of your transaction makes reversal harder.",
            "Coffee-money and house-money deserve different patience. Match confirmation depth to consequence.",
            "Exchanges set their own deposit thresholds. Those rules are risk policies, not cosmic law.",
            "If someone demands you treat an unconfirmed tx as sacred settlement, slow down.",
          ],
        },
      ],
      densify: [
        ["what-is-dogecoin", "tipping-culture"],
        ["culture-and-memes", "tipping-culture"],
        ["wallets-explained", "hardware-wallets"],
        ["how-dogecoin-works", "confirmations-explained"],
      ],
    },
    {
      id: "pass-02",
      pages: [
        {
          slug: "social-engineering",
          title: "Social engineering 101",
          pillar: "safety",
          summary: "How trust is hacked without touching code.",
          hook: "The vulnerability is often kindness.",
          tags: ["scams", "psychology"],
          related: ["scam-patterns-uk", "support-impersonation", "phishing-red-flags", "if-you-got-scammed", "fake-giveaways"],
          body: [
            "Social engineering scripts borrow authority, fear, romance, or greed — then ask for a small irreversible step.",
            "UK phone and WhatsApp vectors are common. Verify through a second channel you initiate.",
            "Practice saying ‘I’ll call you back on the official number.’ It feels rude. It is adult.",
            "Safety literacy is emotional literacy under pressure.",
          ],
        },
        {
          slug: "dogecoin-history",
          title: "A short Dogecoin history",
          pillar: "clarity",
          summary: "From joke fork to cultural fixture — the arc without mythology overload.",
          hook: "Origin stories explain tone. They do not predict price.",
          tags: ["history", "culture"],
          related: ["what-is-dogecoin", "is-dogecoin-a-joke", "culture-and-memes", "dogecoin-vs-bitcoin", "why-uk-domain"],
          body: [
            "Dogecoin launched in 2013 as a light-hearted fork culture experiment and somehow refused to die.",
            "Attention cycles came in waves. Each wave onboarded new humans and new predators.",
            "History helps you spot recycled narratives dressed as novelty.",
            "Read it for orientation, not nostalgia investment thesis cosplay.",
          ],
        },
        {
          slug: "meetups-and-irl",
          title: "Meetups and IRL",
          pillar: "belonging",
          summary: "How to gather in the UK without turning into a pitch room.",
          hook: "The best meetup ends with people safer than they arrived.",
          tags: ["uk", "community", "irl"],
          related: ["uk-community-pulse", "phishing-red-flags", "first-doge-checklist", "why-uk-domain", "tipping-culture"],
          body: [
            "Open with a safety five minutes. Normalise seed hygiene talk like you normalise fire exits.",
            "Avoid on-stage price prophecy. Teach a skill: address verify, wallet backup, scam teardown.",
            "Publish notes afterward so remote UK folks inherit the signal.",
            "Belonging scales when IRL generosity meets online clarity.",
          ],
        },
      ],
      densify: [
        ["scam-patterns-uk", "social-engineering"],
        ["what-is-dogecoin", "dogecoin-history"],
        ["uk-community-pulse", "meetups-and-irl"],
        ["is-dogecoin-a-joke", "dogecoin-history"],
      ],
    },
    {
      id: "pass-03",
      pages: [
        {
          slug: "password-and-2fa",
          title: "Passwords and 2FA",
          pillar: "safety",
          summary: "Exchange hygiene that prevents the boring disasters.",
          hook: "Most ‘hacks’ are reused passwords with better marketing.",
          tags: ["opsec", "exchange"],
          related: ["exchange-vs-wallet", "scam-patterns-uk", "support-impersonation", "self-custody-checklist", "common-mistakes"],
          body: [
            "Unique passwords. A manager. App-based or hardware 2FA over SMS when you can.",
            "SIM-swap is a UK-relevant threat. SMS 2FA is better than nothing and worse than app 2FA.",
            "Withdrawal allowlists add friction that saves careers.",
            "Boring security is elite security.",
          ],
        },
        {
          slug: "reading-block-explorers",
          title: "Reading block explorers",
          pillar: "clarity",
          summary: "How to verify a send yourself without trusting a screenshot.",
          hook: "Screenshots lie. Explorers gossip truthfully.",
          tags: ["tools", "network"],
          related: ["confirmations-explained", "how-dogecoin-works", "address-hygiene", "fees-and-speed", "common-mistakes"],
          body: [
            "Paste a txid into a reputable explorer. Confirm amount, addresses, and confirmation count.",
            "Never trust a cropped image from a stranger as proof of payment.",
            "Learn the difference between ‘broadcast’ and ‘confirmed.’",
            "Clarity tools turn anxiety into checkable facts.",
          ],
        },
        {
          slug: "creators-and-builders",
          title: "Creators and builders",
          pillar: "belonging",
          summary: "Making things in the DOGE orbit without extractive hustle energy.",
          hook: "Build for the pack, not the extract.",
          tags: ["builders", "community"],
          related: ["uk-community-pulse", "join-the-list", "culture-and-memes", "why-uk-domain", "proof-matrix"],
          body: [
            "Tools, explainers, art, and meetup ops all count as building.",
            "Disclose affiliations. Hidden bags plus loud advice is a trust tax.",
            "Ship useful docs. Memes without manuals strand newcomers.",
            "UK builders: document in .co.uk English — dry, clear, kind.",
          ],
        },
      ],
      densify: [
        ["exchange-vs-wallet", "password-and-2fa"],
        ["how-dogecoin-works", "reading-block-explorers"],
        ["uk-community-pulse", "creators-and-builders"],
        ["join-the-list", "creators-and-builders"],
      ],
    },
  ],
};
